// Code generated by mockery v2.53.6. DO NOT EDIT.

package component

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockrepositoryDeletionGit is an autogenerated mock type for the repositoryDeletionGit type
type MockrepositoryDeletionGit struct {
	mock.Mock
}

type MockrepositoryDeletionGit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockrepositoryDeletionGit) EXPECT() *MockrepositoryDeletionGit_Expecter {
	return &MockrepositoryDeletionGit_Expecter{mock: &_m.Mock}
}

// DeleteRepo provides a mock function with given fields: ctx, relativePath
func (_m *MockrepositoryDeletionGit) DeleteRepo(ctx context.Context, relativePath string) error {
	ret := _m.Called(ctx, relativePath)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRepo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, relativePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockrepositoryDeletionGit_DeleteRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRepo'
type MockrepositoryDeletionGit_DeleteRepo_Call struct {
	*mock.Call
}

// DeleteRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - relativePath string
func (_e *MockrepositoryDeletionGit_Expecter) DeleteRepo(ctx interface{}, relativePath interface{}) *MockrepositoryDeletionGit_DeleteRepo_Call {
	return &MockrepositoryDeletionGit_DeleteRepo_Call{Call: _e.mock.On("DeleteRepo", ctx, relativePath)}
}

func (_c *MockrepositoryDeletionGit_DeleteRepo_Call) Run(run func(ctx context.Context, relativePath string)) *MockrepositoryDeletionGit_DeleteRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockrepositoryDeletionGit_DeleteRepo_Call) Return(_a0 error) *MockrepositoryDeletionGit_DeleteRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockrepositoryDeletionGit_DeleteRepo_Call) RunAndReturn(run func(context.Context, string) error) *MockrepositoryDeletionGit_DeleteRepo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockrepositoryDeletionGit creates a new instance of MockrepositoryDeletionGit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockrepositoryDeletionGit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockrepositoryDeletionGit {
	mock := &MockrepositoryDeletionGit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
