// Code generated by mockery v2.53.5. DO NOT EDIT.

package component

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	types "opencsg.com/csghub-server/common/types"
)

// MockWebHookComponent is an autogenerated mock type for the WebHookComponent type
type MockWebHookComponent struct {
	mock.Mock
}

type MockWebHookComponent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebHookComponent) EXPECT() *MockWebHookComponent_Expecter {
	return &MockWebHookComponent_Expecter{mock: &_m.Mock}
}

// DispatchWebHookEvent provides a mock function with no fields
func (_m *MockWebHookComponent) DispatchWebHookEvent() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DispatchWebHookEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebHookComponent_DispatchWebHookEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchWebHookEvent'
type MockWebHookComponent_DispatchWebHookEvent_Call struct {
	*mock.Call
}

// DispatchWebHookEvent is a helper method to define mock.On call
func (_e *MockWebHookComponent_Expecter) DispatchWebHookEvent() *MockWebHookComponent_DispatchWebHookEvent_Call {
	return &MockWebHookComponent_DispatchWebHookEvent_Call{Call: _e.mock.On("DispatchWebHookEvent")}
}

func (_c *MockWebHookComponent_DispatchWebHookEvent_Call) Run(run func()) *MockWebHookComponent_DispatchWebHookEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebHookComponent_DispatchWebHookEvent_Call) Return(_a0 error) *MockWebHookComponent_DispatchWebHookEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebHookComponent_DispatchWebHookEvent_Call) RunAndReturn(run func() error) *MockWebHookComponent_DispatchWebHookEvent_Call {
	_c.Call.Return(run)
	return _c
}

// HandleWebHook provides a mock function with given fields: ctx, event
func (_m *MockWebHookComponent) HandleWebHook(ctx context.Context, event *types.WebHookRecvEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebHook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.WebHookRecvEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebHookComponent_HandleWebHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebHook'
type MockWebHookComponent_HandleWebHook_Call struct {
	*mock.Call
}

// HandleWebHook is a helper method to define mock.On call
//   - ctx context.Context
//   - event *types.WebHookRecvEvent
func (_e *MockWebHookComponent_Expecter) HandleWebHook(ctx interface{}, event interface{}) *MockWebHookComponent_HandleWebHook_Call {
	return &MockWebHookComponent_HandleWebHook_Call{Call: _e.mock.On("HandleWebHook", ctx, event)}
}

func (_c *MockWebHookComponent_HandleWebHook_Call) Run(run func(ctx context.Context, event *types.WebHookRecvEvent)) *MockWebHookComponent_HandleWebHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.WebHookRecvEvent))
	})
	return _c
}

func (_c *MockWebHookComponent_HandleWebHook_Call) Return(_a0 error) *MockWebHookComponent_HandleWebHook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebHookComponent_HandleWebHook_Call) RunAndReturn(run func(context.Context, *types.WebHookRecvEvent) error) *MockWebHookComponent_HandleWebHook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebHookComponent creates a new instance of MockWebHookComponent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebHookComponent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebHookComponent {
	mock := &MockWebHookComponent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
