SET statement_timeout = 0;

--bun:split
--add opencompass as namespace for all tag_rules created in 20241111095847_init_tag_rule.up.sql
--then drop the default the value
ALTER TABLE public.tag_rules ADD COLUMN IF NOT EXISTS namespace VARCHAR DEFAULT 'opencompass';
ALTER TABLE public.tag_rules ALTER COLUMN namespace DROP DEFAULT;
ALTER TABLE public.tag_rules ADD COLUMN IF NOT EXISTS source VARCHAR DEFAULT 'ms';
ALTER TABLE public.tag_rules ALTER COLUMN source DROP DEFAULT;
ALTER TABLE public.tag_rules DROP CONSTRAINT unique_tag_rules;
ALTER TABLE public.tag_rules ADD CONSTRAINT unique_tag_rules UNIQUE (namespace,repo_name, category);

--bun:split
INSERT INTO public.tags ("name", category, "group", "scope", built_in, show_name) VALUES('lm-evaluation-harness', 'runtime_framework', 'evaluation', 'model', true, 'lm-evaluation-harness') ON CONFLICT ("name", category, scope) DO NOTHING;
INSERT INTO public.tags ("name", category, "group", "scope", built_in, show_name) VALUES('lm-evaluation-harness', 'runtime_framework', 'evaluation', 'dataset', true, 'lm-evaluation-harness') ON CONFLICT ("name", category, scope) DO NOTHING;
INSERT INTO public.tags ("name", category, "group", "scope", built_in, show_name, created_at, updated_at) VALUES('Benchmark', 'evaluation', '', 'dataset', true, 'Benchmark', '2024-11-26 10:42:12.939', '2024-11-26 10:42:12.939') ON CONFLICT ("name", category, scope) DO NOTHING;

--bun:split
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HCAI', 'metabench', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'bigbench', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('lighteval', 'MATH-Hard', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('ofir408', 'MedConceptsQA', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('pbevan11', 'EQ-Bench', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('tinyBenchmarks', 'tinyAI2_arc', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('tinyBenchmarks', 'tinyGSM8k', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('tinyBenchmarks', 'tinyHellaswag', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('tinyBenchmarks', 'tinyMMLU', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('tinyBenchmarks', 'tinyTruthfulQA', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('tinyBenchmarks', 'tinyWinogrande', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('wis-k', 'instruction-following-eval', 'evaluation', 'Benchmark', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('SaylorTwift', 'bbh', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('TAUR-Lab', 'MuSR', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('ambean', 'lingOly', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('facebook', 'anli', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('openai', 'gsm8k', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('inverse-scaling', 'NeQA', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('inverse-scaling', 'hindsight-neglect-10shot', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('inverse-scaling', 'quote-repetition', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('inverse-scaling', 'redefine-math', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('mathemakitten', 'winobias_antistereotype_test_v5', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('qintongli', 'GSM-Plus', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'swag', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('cambridgeltl', 'xcopa', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('facebook', 'anli', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Rowan', 'hellaswag', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('ybisk', 'piqa', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('ErnestSDavis', 'winograd_wsc', 'evaluation', 'Reasoning', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;

INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('AYueksel', 'TurkishMMLU', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Hennara', 'copa_ar', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Hennara', 'pica_ar', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('LumiOpen', 'arc_challenge_mt', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('TIGER-Lab', 'MMLU-Pro', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('alexandrainst', 'm_arc', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('alexandrainst', 'm_hellaswag', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('alexandrainst', 'm_mmlu', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('alexandrainst', 'm_truthfulqa', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'ai2_arc', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'paloma', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('google', 'IFEval', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-aqua-rat', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-biology', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-chemistry', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-chinese', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-english', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-geography', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-history', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-mathcloze', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-mathqa', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-gaokao-physics', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-jec-qa-ca', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-jec-qa-kd', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-logiqa-en', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-logiqa-zh', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-lsat-ar', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-lsat-lr', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-lsat-rc', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-math', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-sat-en', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-sat-en-without-passage', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hails', 'agieval-sat-math', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('mideind', 'icelandic-arc-challenge', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'math_qa', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('openlifescienceai', 'medmcqa', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'sciq', 'evaluation', 'Examination', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;

INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HAERAE-HUB', 'HAE_RAE_BENCH', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HAERAE-HUB', 'KMMLU', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HAERAE-HUB', 'KMMLU-HARD', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Idavidrein', 'gpqa', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Muennighoff', 'babi', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('masakhane', 'afrimgsm', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('masakhane', 'afrimgsm-translate-test', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('masakhane', 'afrimmlu', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('masakhane', 'afrimmlu-translate-test', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('masakhane', 'afrixnli', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('masakhane', 'afrixnli-translate-test', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('google-research-datasets', 'nq_open', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'openbookqa', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('tau', 'commonsense_qa', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('mandarjoshi', 'trivia_qa', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('truthfulqa', 'truthful_qa', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Stanford', 'web_questions', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('community-datasets', 'qa4mre', 'evaluation', 'Knowledge', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;


INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('GBaker', 'MedQA-USMLE-4-options-hf', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'BertaQA', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'EusExams', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'EusProficiency', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'EusTrivia', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'MGSM-eu', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'XCOPA-eu', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'wnli-eu', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('HiTZ', 'xnli-eu', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('facebook', 'belebele', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('nyu-mll', 'glue', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('hitachi-nlp', 'FLD.v2', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('maximegmd', 'glianorex', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('google-research-datasets', 'paws-x', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('facebook', 'xnli', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('google', 'xquad', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('cimec', 'lambada', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('CogComp', 'mc_taco', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'social_i_qa', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('LSDSem', 'story_cloze', 'evaluation', 'Understanding', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;

INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('CM', 'codexglue_code2text_go', 'evaluation', 'Code', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('CM', 'codexglue_code2text_java', 'evaluation', 'Code', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('CM', 'codexglue_code2text_javascript', 'evaluation', 'Code', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('CM', 'codexglue_code2text_php', 'evaluation', 'Code', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('CM', 'codexglue_code2text_python', 'evaluation', 'Code', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('CM', 'codexglue_code2text_ruby', 'evaluation', 'Code', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'real-toxicity-prompts', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Albertmade', 'into-the-unknown', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Albertmade', 'memo-trap', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Albertmade', 'modus-tollens', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Albertmade', 'pattern-matching-suppression', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Albertmade', 'repetitive-algebra', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Albertmade', 'sig-figs', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('BSC-LT', 'COPA-es', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('BSC-LT', 'openbookqa-es', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('EleutherAI', 'headqa', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('EleutherAI', 'winogenerated', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('Geralt-Targaryen', 'MELA', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('NeelNanda', 'pile-10k', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('nyu-mll', 'blimp', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('cais', 'wmdp', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('skg', 'toxigen-data', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('wmt', 'wmt14', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('wmt', 'wmt16', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('allenai', 'winogrande', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('aps', 'super_glue', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('nyu-mll', 'blimp', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('facebook', 'xnli', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('nyu-mll', 'glue', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;
INSERT INTO public.tag_rules (namespace, "repo_name", category, "tag_name", "repo_type", runtime_framework, source) VALUES ('IWSLT', 'iwslt2017', 'evaluation', 'Other', 'dataset', 'lm-evaluation-harness', 'hf') ON CONFLICT (namespace, "repo_name", category) DO NOTHING;



