SET statement_timeout = 0;

--bun:split

ALTER TABLE cluster_infos ADD COLUMN IF NOT EXISTS endpoint VARCHAR;

ALTER TABLE cluster_infos ADD COLUMN IF NOT EXISTS status VARCHAR;

ALTER TABLE cluster_infos ADD COLUMN IF NOT EXISTS mode VARCHAR;

ALTER TABLE cluster_infos ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE cluster_infos ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
