SET statement_timeout = 0;

--bun:split

ALTER TABLE collection_repositories ADD COLUMN IF NOT EXISTS remark TEXT DEFAULT '';

ALTER TABLE collection_repositories ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE collection_repositories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
