{
 "title": "Golang runtime",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"go_info|process_runtime_go_goroutines\",job!=\"\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"go_info|process_runtime_go_goroutines\",job!=\"\",job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Golang runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  process_runtime_go_goroutines{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Goroutines"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Golang process uptime.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  runtime_uptime_milliseconds_total{job!=\"\",job=~\"$job\",instance=~\"$instance\"}/1000\n)\nor\navg by (job,instance) (\n  runtime_uptime{job!=\"\",job=~\"$job\",instance=~\"$instance\"}/1000\n)\nor\navg by (job,instance) (\n  time()-process_start_time_seconds{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "CGo calls",
   "type": "stat",
   "description": "Number of cgo calls made by the current process",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  rate(go_cgo_go_to_c_calls_calls_total{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\nor\navg by (job,instance) (\n  rate(process_runtime_go_cgo_calls{job!=\"\",job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)",
     "legendFormat": "{{instance}}: CGo calls"
    }
   ]
  },
  { "title": "Go runtime: memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory heap objects",
   "type": "timeseries",
   "description": "Number of allocated heap objects.\nThis changes as GC is performed and new objects are allocated.\n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  go_memstats_heap_objects{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_objects{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Heap allocated objects"
    }
   ]
  },
  {
   "title": "Memory heap",
   "type": "timeseries",
   "description": "Memory used heap.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  go_memstats_heap_sys_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Memory reserved from system by heap"
    },
    {
     "expr": "avg by (job,instance) (\n  go_memstats_heap_alloc_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_alloc_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_alloc{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Heap objects, bytes"
    },
    {
     "expr": "avg by (job,instance) (\n  go_memstats_heap_idle_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_idle_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_idle{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Heap idle spans, bytes"
    },
    {
     "expr": "avg by (job,instance) (\n  go_memstats_heap_inuse_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_inuse_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_inuse{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Heap in-use spans, bytes"
    },
    {
     "expr": "avg by (job,instance) (\n  go_memstats_heap_released_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_released_bytes{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  process_runtime_go_mem_heap_released{job!=\"\",job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Heap released, bytes"
    }
   ]
  }
 ]
}