with-expecter: true
dir: "_mocks/{{.PackagePath}}"
packages:
    opencsg.com/csghub-server/component:
        config:
        interfaces:
            RepoComponent:
    opencsg.com/csghub-server/user/component:
        config:
        interfaces:
            MemberComponent:
    opencsg.com/csghub-server/builder/store/database:
        config:
        interfaces:
            UserStore:
            NamespaceStore:
            LicenseStore:
            MirrorStore:
            RepoStore:
            OrgStore:
            MemberStore:
            ModelStore:
            SpaceResourceStore:
            TagStore:
            DatasetStore:
            PromptConversationStore:
            PromptPrefixStore:
            LLMConfigStore:
            PromptStore:
            UserLikesStore:
            AccountStatementStore:
            AccountOrderStore:
            AccountPriceStore:
            AccountBillStore:
            AccountEventStore:
            AccountMeteringStore:
            AccountPresentStore:
    opencsg.com/csghub-server/builder/rpc:
        config:
        interfaces:
            UserSvcClient:
    opencsg.com/csghub-server/builder/sensitive:
        config:
        interfaces:
            GreenClient:
            Green2022Client:
    opencsg.com/csghub-server/builder/git/gitserver:
        config:
        interfaces:
            GitServer:
    opencsg.com/csghub-server/builder/git/membership:
        config:
        interfaces:
            GitMemerShip:
    opencsg.com/csghub-server/builder/rsa:
        config:
        interfaces:
            KeysReader:
    opencsg.com/csghub-server/mirror/cache:
        config:
        interfaces:
            Cache:
