with-expecter: true
dir: "_mocks/{{.PackagePath}}"
# new from v2.49.0, for more detail please refer to:
# https://github.com/vektra/mockery/commit/13fc60740a1eab3fc705fcc131a4b9a6eacfd0fe#diff-4bc8f03915f15ecf2cb9965592fcf933bb06986003613b5633a8dea7962c31a9R40
resolve-type-alias: false
packages:
  io:
    config:
    interfaces:
      Reader:
  opencsg.com/csghub-server/component:
    config:
    interfaces:
      RepoComponent:
      TagComponent:
      AccountingComponent:
      SpaceComponent:
      SpaceResourceComponent:
      RuntimeArchitectureComponent:
      SensitiveComponent:
      CodeComponent:
      PromptComponent:
      ModelComponent:
      UserComponent:
      GitHTTPComponent:
      DiscussionComponent:
      DatasetComponent:
      CollectionComponent:
      BroadcastComponent:
      InternalComponent:
      MirrorSourceComponent:
      MirrorComponent:
      ImportComponent:
      EvaluationComponent:
      RecomComponent:
      MultiSyncComponent:
      ModelTreeComponent:
      SpaceTemplateComponent:
      MCPServerComponent:
      MonitorComponent:
  opencsg.com/csghub-server/component/callback:
    config:
    interfaces:
      SyncVersionGenerator:
      GitCallbackComponent:
  opencsg.com/csghub-server/user/component:
    config:
    interfaces:
      MemberComponent:
      OrganizationComponent:
  opencsg.com/csghub-server/builder/store/database:
    config:
      all: True
  opencsg.com/csghub-server/builder/rpc:
    config:
    interfaces:
      UserSvcClient:
      ModerationSvcClient:
  opencsg.com/csghub-server/builder/sensitive:
    config:
    interfaces:
      GreenClient:
      Green2022Client:
      SensitiveChecker:
  opencsg.com/csghub-server/builder/git/gitserver:
    config:
    interfaces:
      GitServer:
  opencsg.com/csghub-server/builder/git/mirrorserver:
    config:
    interfaces:
      MirrorServer:
  opencsg.com/csghub-server/builder/git/membership:
    config:
    interfaces:
      GitMemerShip:
  opencsg.com/csghub-server/builder/rsa:
    config:
    interfaces:
      KeysReader:
  opencsg.com/csghub-server/builder/prometheus:
    config:
    interfaces:
      PrometheusClient:  
  opencsg.com/csghub-server/mirror/cache:
    config:
    interfaces:
      Cache:
  opencsg.com/csghub-server/common/types:
    config:
    interfaces:
      SensitiveRequestV2:
  opencsg.com/csghub-server/mq:
    config:
    interfaces:
      MessageQueue:
  opencsg.com/csghub-server/builder/store/s3:
    config:
    interfaces:
      Client:
      Core:
  opencsg.com/csghub-server/mirror/queue:
    config:
    interfaces:
      PriorityQueue:
  opencsg.com/csghub-server/builder/deploy:
    config:
    interfaces:
      Deployer:
  opencsg.com/csghub-server/builder/deploy/scheduler:
    config:
    interfaces:
      Scheduler:
  opencsg.com/csghub-server/builder/deploy/imagerunner:
    config:
    interfaces:
      Runner:
  opencsg.com/csghub-server/builder/deploy/imagebuilder:
    config:
    interfaces:
      Builder:
  opencsg.com/csghub-server/accounting/component:
    config:
    interfaces:
      AccountingUserComponent:
      AccountingStatementComponent:
      AccountingBillComponent:
      AccountingPresentComponent:
      MeteringComponent:
      AccountingEventComponent:
      AccountingPriceComponent:
      AccountingOrderComponent:
  opencsg.com/csghub-server/builder/accounting:
    config:
    interfaces:
      AccountingClient:
  opencsg.com/csghub-server/builder/parquet:
    config:
    interfaces:
      Reader:
      LimitOffsetCountReader:
  opencsg.com/csghub-server/builder/multisync:
    config:
    interfaces:
      Client:
  opencsg.com/csghub-server/builder/store/cache:
    config:
    interfaces:
      RedisClient:
  github.com/nats-io/nats.go/jetstream:
    config:
    interfaces:
      Msg:
  go.temporal.io/sdk/client:
    config:
    interfaces:
      Client:
  opencsg.com/csghub-server/builder/temporal:
    config:
    interfaces:
      Client:
      ScheduleClient:
  opencsg.com/csghub-server/builder/importer:
    config:
    interfaces:
      Importer:
  gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypb:
    config:
    interfaces:
      RepositoryServiceClient:
      CommitServiceClient:
      BlobServiceClient:
      RefServiceClient:
      DiffServiceClient:
      OperationServiceClient:
      SmartHTTPServiceClient:
      RemoteServiceClient:
  opencsg.com/csghub-server/builder/dataviewer:
    config:
    interfaces:
      DataviewerClient:
  opencsg.com/csghub-server/dataviewer/workflows:
    config:
    interfaces:
      DataViewerActivity:
  opencsg.com/csghub-server/dataviewer/component:
    config:
    interfaces:
      DatasetViewerComponent:
  opencsg.com/csghub-server/aigateway/component:
    config:
      all: true
  opencsg.com/csghub-server/aigateway/handler:
    config:
    interfaces:
      CommonResponseWriter:
  opencsg.com/csghub-server/aigateway/token:
    config:
      all: true
  opencsg.com/csghub-server/notification/component:
    config:
    interfaces:
      NotificationComponent:
      MailComponent:
