auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  # Add this block to specify the WAL directory.
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

###
schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  # Global limits applied at the distributor.
  ingestion_rate_mb: 25
  ingestion_burst_size_mb: 50
  # Per-stream rate limits to avoid 429 errors from high-volume log sources.
  # This value is in BYTES per second. We set it to 15MB/s.
  per_stream_rate_limit: 15728640
  # This value is in BYTES. We set it to 30MB.
  per_stream_rate_limit_burst: 31457280
  max_query_lookback: 168h
  retention_period: 168h
  # Increase the number of allowed concurrent tailing requests per tenant.
  # The default is 10.
  max_concurrent_tail_requests: 10000
  # Maximum number of active streams per user.
  max_streams_per_user: 10000

compactor:
  working_directory:  /tmp/retention
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
