apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
