FROM opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/debian:bookworm-slim

RUN sed -i 's|http://deb.debian.org/debian|http://mirrors.aliyun.com/debian|g' /etc/apt/sources.list.d/debian.sources && \
    sed -i 's|http://deb.debian.org/debian-security|http://mirrors.aliyun.com/debian-security|g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt-get install -y --no-install-recommends \
    cron \
    wget \
    curl \
    procps \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://opencsg-public-resource.oss-cn-beijing.aliyuncs.com/tools/jq-linux-amd64 -O /usr/bin/jq && \
    chmod 755 /usr/bin/jq

RUN mkdir -p ~/.duckdb/extensions/v0.9.2/linux_amd64 && \
    wget https://opencsg-public-resource.oss-cn-beijing.aliyuncs.com/tools/duckdb/httpfs.duckdb_extension -O ~/.duckdb/extensions/v0.9.2/linux_amd64/httpfs.duckdb_extension && \
    chmod 755 ~/.duckdb/extensions/v0.9.2/linux_amd64/httpfs.duckdb_extension && \
    wget https://extensions.duckdb.org/v0.9.2/linux_amd64/json.duckdb_extension.gz -O ~/.duckdb/extensions/v0.9.2/linux_amd64/json.duckdb_extension.gz && \
    gunzip ~/.duckdb/extensions/v0.9.2/linux_amd64/json.duckdb_extension.gz && \
    chmod 755 ~/.duckdb/extensions/v0.9.2/linux_amd64/json.duckdb_extension

# docker build -t opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/csghub_server:base-3.0-runtime -f Dockerfile-base-runtime .