// Code generated by mockery v2.53.6. DO NOT EDIT.

package component

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	types "opencsg.com/csghub-server/aigateway/types"
)

// MockAutoModelRouter is an autogenerated mock type for the AutoModelRouter type
type MockAutoModelRouter struct {
	mock.Mock
}

type MockAutoModelRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutoModelRouter) EXPECT() *MockAutoModelRouter_Expecter {
	return &MockAutoModelRouter_Expecter{mock: &_m.Mock}
}

// Available provides a mock function with given fields: ctx
func (_m *MockAutoModelRouter) Available(ctx context.Context) bool {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Available")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockAutoModelRouter_Available_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Available'
type MockAutoModelRouter_Available_Call struct {
	*mock.Call
}

// Available is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAutoModelRouter_Expecter) Available(ctx interface{}) *MockAutoModelRouter_Available_Call {
	return &MockAutoModelRouter_Available_Call{Call: _e.mock.On("Available", ctx)}
}

func (_c *MockAutoModelRouter_Available_Call) Run(run func(ctx context.Context)) *MockAutoModelRouter_Available_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAutoModelRouter_Available_Call) Return(_a0 bool) *MockAutoModelRouter_Available_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAutoModelRouter_Available_Call) RunAndReturn(run func(context.Context) bool) *MockAutoModelRouter_Available_Call {
	_c.Call.Return(run)
	return _c
}

// ModelID provides a mock function with no fields
func (_m *MockAutoModelRouter) ModelID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModelID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAutoModelRouter_ModelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModelID'
type MockAutoModelRouter_ModelID_Call struct {
	*mock.Call
}

// ModelID is a helper method to define mock.On call
func (_e *MockAutoModelRouter_Expecter) ModelID() *MockAutoModelRouter_ModelID_Call {
	return &MockAutoModelRouter_ModelID_Call{Call: _e.mock.On("ModelID")}
}

func (_c *MockAutoModelRouter_ModelID_Call) Run(run func()) *MockAutoModelRouter_ModelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAutoModelRouter_ModelID_Call) Return(_a0 string) *MockAutoModelRouter_ModelID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAutoModelRouter_ModelID_Call) RunAndReturn(run func() string) *MockAutoModelRouter_ModelID_Call {
	_c.Call.Return(run)
	return _c
}

// Select provides a mock function with given fields: ctx, input, candidates
func (_m *MockAutoModelRouter) Select(ctx context.Context, input types.AutoRouteInput, candidates []types.Model) (*types.AutoRouteDecision, error) {
	ret := _m.Called(ctx, input, candidates)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 *types.AutoRouteDecision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AutoRouteInput, []types.Model) (*types.AutoRouteDecision, error)); ok {
		return rf(ctx, input, candidates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AutoRouteInput, []types.Model) *types.AutoRouteDecision); ok {
		r0 = rf(ctx, input, candidates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.AutoRouteDecision)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AutoRouteInput, []types.Model) error); ok {
		r1 = rf(ctx, input, candidates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAutoModelRouter_Select_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Select'
type MockAutoModelRouter_Select_Call struct {
	*mock.Call
}

// Select is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.AutoRouteInput
//   - candidates []types.Model
func (_e *MockAutoModelRouter_Expecter) Select(ctx interface{}, input interface{}, candidates interface{}) *MockAutoModelRouter_Select_Call {
	return &MockAutoModelRouter_Select_Call{Call: _e.mock.On("Select", ctx, input, candidates)}
}

func (_c *MockAutoModelRouter_Select_Call) Run(run func(ctx context.Context, input types.AutoRouteInput, candidates []types.Model)) *MockAutoModelRouter_Select_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AutoRouteInput), args[2].([]types.Model))
	})
	return _c
}

func (_c *MockAutoModelRouter_Select_Call) Return(_a0 *types.AutoRouteDecision, _a1 error) *MockAutoModelRouter_Select_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAutoModelRouter_Select_Call) RunAndReturn(run func(context.Context, types.AutoRouteInput, []types.Model) (*types.AutoRouteDecision, error)) *MockAutoModelRouter_Select_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAutoModelRouter creates a new instance of MockAutoModelRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutoModelRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutoModelRouter {
	mock := &MockAutoModelRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
