// Code generated by mockery v2.53.5. DO NOT EDIT.

package component

import (
	commontypes "opencsg.com/csghub-server/common/types"

	mock "github.com/stretchr/testify/mock"

	types "opencsg.com/csghub-server/aigateway/types"
)

// MockLLMLogRecorder is an autogenerated mock type for the LLMLogRecorder type
type MockLLMLogRecorder struct {
	mock.Mock
}

type MockLLMLogRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMLogRecorder) EXPECT() *MockLLMLogRecorder_Expecter {
	return &MockLLMLogRecorder_Expecter{mock: &_m.Mock}
}

// AppendCompletionChunk provides a mock function with given fields: _a0
func (_m *MockLLMLogRecorder) AppendCompletionChunk(_a0 types.ChatCompletionChunk) {
	_m.Called(_a0)
}

// MockLLMLogRecorder_AppendCompletionChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendCompletionChunk'
type MockLLMLogRecorder_AppendCompletionChunk_Call struct {
	*mock.Call
}

// AppendCompletionChunk is a helper method to define mock.On call
//   - _a0 types.ChatCompletionChunk
func (_e *MockLLMLogRecorder_Expecter) AppendCompletionChunk(_a0 interface{}) *MockLLMLogRecorder_AppendCompletionChunk_Call {
	return &MockLLMLogRecorder_AppendCompletionChunk_Call{Call: _e.mock.On("AppendCompletionChunk", _a0)}
}

func (_c *MockLLMLogRecorder_AppendCompletionChunk_Call) Run(run func(_a0 types.ChatCompletionChunk)) *MockLLMLogRecorder_AppendCompletionChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ChatCompletionChunk))
	})
	return _c
}

func (_c *MockLLMLogRecorder_AppendCompletionChunk_Call) Return() *MockLLMLogRecorder_AppendCompletionChunk_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLLMLogRecorder_AppendCompletionChunk_Call) RunAndReturn(run func(types.ChatCompletionChunk)) *MockLLMLogRecorder_AppendCompletionChunk_Call {
	_c.Run(run)
	return _c
}

// Completion provides a mock function with given fields: _a0
func (_m *MockLLMLogRecorder) Completion(_a0 types.ChatCompletion) {
	_m.Called(_a0)
}

// MockLLMLogRecorder_Completion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Completion'
type MockLLMLogRecorder_Completion_Call struct {
	*mock.Call
}

// Completion is a helper method to define mock.On call
//   - _a0 types.ChatCompletion
func (_e *MockLLMLogRecorder_Expecter) Completion(_a0 interface{}) *MockLLMLogRecorder_Completion_Call {
	return &MockLLMLogRecorder_Completion_Call{Call: _e.mock.On("Completion", _a0)}
}

func (_c *MockLLMLogRecorder_Completion_Call) Run(run func(_a0 types.ChatCompletion)) *MockLLMLogRecorder_Completion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.ChatCompletion))
	})
	return _c
}

func (_c *MockLLMLogRecorder_Completion_Call) Return() *MockLLMLogRecorder_Completion_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLLMLogRecorder_Completion_Call) RunAndReturn(run func(types.ChatCompletion)) *MockLLMLogRecorder_Completion_Call {
	_c.Run(run)
	return _c
}

// Record provides a mock function with no fields
func (_m *MockLLMLogRecorder) Record() (*commontypes.LLMLogRecord, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 *commontypes.LLMLogRecord
	var r1 error
	if rf, ok := ret.Get(0).(func() (*commontypes.LLMLogRecord, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *commontypes.LLMLogRecord); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*commontypes.LLMLogRecord)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLMLogRecorder_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockLLMLogRecorder_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
func (_e *MockLLMLogRecorder_Expecter) Record() *MockLLMLogRecorder_Record_Call {
	return &MockLLMLogRecorder_Record_Call{Call: _e.mock.On("Record")}
}

func (_c *MockLLMLogRecorder_Record_Call) Run(run func()) *MockLLMLogRecorder_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLLMLogRecorder_Record_Call) Return(_a0 *commontypes.LLMLogRecord, _a1 error) *MockLLMLogRecorder_Record_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLMLogRecorder_Record_Call) RunAndReturn(run func() (*commontypes.LLMLogRecord, error)) *MockLLMLogRecorder_Record_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLMLogRecorder creates a new instance of MockLLMLogRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMLogRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMLogRecorder {
	mock := &MockLLMLogRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
