// Code generated by mockery v2.53.5. DO NOT EDIT.

package component

import (
	context "context"

	openai "github.com/openai/openai-go/v3"
	mock "github.com/stretchr/testify/mock"

	rpc "opencsg.com/csghub-server/builder/rpc"

	types "opencsg.com/csghub-server/aigateway/types"
)

// MockModeration is an autogenerated mock type for the Moderation type
type MockModeration struct {
	mock.Mock
}

type MockModeration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModeration) EXPECT() *MockModeration_Expecter {
	return &MockModeration_Expecter{mock: &_m.Mock}
}

// CheckChatNonStreamResponse provides a mock function with given fields: ctx, completion
func (_m *MockModeration) CheckChatNonStreamResponse(ctx context.Context, completion types.ChatCompletion) (*rpc.CheckResult, error) {
	ret := _m.Called(ctx, completion)

	if len(ret) == 0 {
		panic("no return value specified for CheckChatNonStreamResponse")
	}

	var r0 *rpc.CheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatCompletion) (*rpc.CheckResult, error)); ok {
		return rf(ctx, completion)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatCompletion) *rpc.CheckResult); ok {
		r0 = rf(ctx, completion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.CheckResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ChatCompletion) error); ok {
		r1 = rf(ctx, completion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModeration_CheckChatNonStreamResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckChatNonStreamResponse'
type MockModeration_CheckChatNonStreamResponse_Call struct {
	*mock.Call
}

// CheckChatNonStreamResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - completion types.ChatCompletion
func (_e *MockModeration_Expecter) CheckChatNonStreamResponse(ctx interface{}, completion interface{}) *MockModeration_CheckChatNonStreamResponse_Call {
	return &MockModeration_CheckChatNonStreamResponse_Call{Call: _e.mock.On("CheckChatNonStreamResponse", ctx, completion)}
}

func (_c *MockModeration_CheckChatNonStreamResponse_Call) Run(run func(ctx context.Context, completion types.ChatCompletion)) *MockModeration_CheckChatNonStreamResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ChatCompletion))
	})
	return _c
}

func (_c *MockModeration_CheckChatNonStreamResponse_Call) Return(_a0 *rpc.CheckResult, _a1 error) *MockModeration_CheckChatNonStreamResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModeration_CheckChatNonStreamResponse_Call) RunAndReturn(run func(context.Context, types.ChatCompletion) (*rpc.CheckResult, error)) *MockModeration_CheckChatNonStreamResponse_Call {
	_c.Call.Return(run)
	return _c
}

// CheckChatPrompts provides a mock function with given fields: ctx, messages, uuid
func (_m *MockModeration) CheckChatPrompts(ctx context.Context, messages []openai.ChatCompletionMessageParamUnion, uuid string) (*rpc.CheckResult, error) {
	ret := _m.Called(ctx, messages, uuid)

	if len(ret) == 0 {
		panic("no return value specified for CheckChatPrompts")
	}

	var r0 *rpc.CheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []openai.ChatCompletionMessageParamUnion, string) (*rpc.CheckResult, error)); ok {
		return rf(ctx, messages, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []openai.ChatCompletionMessageParamUnion, string) *rpc.CheckResult); ok {
		r0 = rf(ctx, messages, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.CheckResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []openai.ChatCompletionMessageParamUnion, string) error); ok {
		r1 = rf(ctx, messages, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModeration_CheckChatPrompts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckChatPrompts'
type MockModeration_CheckChatPrompts_Call struct {
	*mock.Call
}

// CheckChatPrompts is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []openai.ChatCompletionMessageParamUnion
//   - uuid string
func (_e *MockModeration_Expecter) CheckChatPrompts(ctx interface{}, messages interface{}, uuid interface{}) *MockModeration_CheckChatPrompts_Call {
	return &MockModeration_CheckChatPrompts_Call{Call: _e.mock.On("CheckChatPrompts", ctx, messages, uuid)}
}

func (_c *MockModeration_CheckChatPrompts_Call) Run(run func(ctx context.Context, messages []openai.ChatCompletionMessageParamUnion, uuid string)) *MockModeration_CheckChatPrompts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]openai.ChatCompletionMessageParamUnion), args[2].(string))
	})
	return _c
}

func (_c *MockModeration_CheckChatPrompts_Call) Return(_a0 *rpc.CheckResult, _a1 error) *MockModeration_CheckChatPrompts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModeration_CheckChatPrompts_Call) RunAndReturn(run func(context.Context, []openai.ChatCompletionMessageParamUnion, string) (*rpc.CheckResult, error)) *MockModeration_CheckChatPrompts_Call {
	_c.Call.Return(run)
	return _c
}

// CheckChatStreamResponse provides a mock function with given fields: ctx, chunk, uuid
func (_m *MockModeration) CheckChatStreamResponse(ctx context.Context, chunk types.ChatCompletionChunk, uuid string) (*rpc.CheckResult, error) {
	ret := _m.Called(ctx, chunk, uuid)

	if len(ret) == 0 {
		panic("no return value specified for CheckChatStreamResponse")
	}

	var r0 *rpc.CheckResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatCompletionChunk, string) (*rpc.CheckResult, error)); ok {
		return rf(ctx, chunk, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatCompletionChunk, string) *rpc.CheckResult); ok {
		r0 = rf(ctx, chunk, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.CheckResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ChatCompletionChunk, string) error); ok {
		r1 = rf(ctx, chunk, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModeration_CheckChatStreamResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckChatStreamResponse'
type MockModeration_CheckChatStreamResponse_Call struct {
	*mock.Call
}

// CheckChatStreamResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - chunk types.ChatCompletionChunk
//   - uuid string
func (_e *MockModeration_Expecter) CheckChatStreamResponse(ctx interface{}, chunk interface{}, uuid interface{}) *MockModeration_CheckChatStreamResponse_Call {
	return &MockModeration_CheckChatStreamResponse_Call{Call: _e.mock.On("CheckChatStreamResponse", ctx, chunk, uuid)}
}

func (_c *MockModeration_CheckChatStreamResponse_Call) Run(run func(ctx context.Context, chunk types.ChatCompletionChunk, uuid string)) *MockModeration_CheckChatStreamResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ChatCompletionChunk), args[2].(string))
	})
	return _c
}

func (_c *MockModeration_CheckChatStreamResponse_Call) Return(_a0 *rpc.CheckResult, _a1 error) *MockModeration_CheckChatStreamResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModeration_CheckChatStreamResponse_Call) RunAndReturn(run func(context.Context, types.ChatCompletionChunk, string) (*rpc.CheckResult, error)) *MockModeration_CheckChatStreamResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModeration creates a new instance of MockModeration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModeration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModeration {
	mock := &MockModeration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
