// Code generated by mockery v2.53.5. DO NOT EDIT.

package component

import mock "github.com/stretchr/testify/mock"

// MockLLMLogPublisher is an autogenerated mock type for the LLMLogPublisher type
type MockLLMLogPublisher struct {
	mock.Mock
}

type MockLLMLogPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMLogPublisher) EXPECT() *MockLLMLogPublisher_Expecter {
	return &MockLLMLogPublisher_Expecter{mock: &_m.Mock}
}

// PublishTrainingLog provides a mock function with given fields: message
func (_m *MockLLMLogPublisher) PublishTrainingLog(message []byte) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for PublishTrainingLog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLLMLogPublisher_PublishTrainingLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTrainingLog'
type MockLLMLogPublisher_PublishTrainingLog_Call struct {
	*mock.Call
}

// PublishTrainingLog is a helper method to define mock.On call
//   - message []byte
func (_e *MockLLMLogPublisher_Expecter) PublishTrainingLog(message interface{}) *MockLLMLogPublisher_PublishTrainingLog_Call {
	return &MockLLMLogPublisher_PublishTrainingLog_Call{Call: _e.mock.On("PublishTrainingLog", message)}
}

func (_c *MockLLMLogPublisher_PublishTrainingLog_Call) Run(run func(message []byte)) *MockLLMLogPublisher_PublishTrainingLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockLLMLogPublisher_PublishTrainingLog_Call) Return(_a0 error) *MockLLMLogPublisher_PublishTrainingLog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLLMLogPublisher_PublishTrainingLog_Call) RunAndReturn(run func([]byte) error) *MockLLMLogPublisher_PublishTrainingLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLMLogPublisher creates a new instance of MockLLMLogPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMLogPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMLogPublisher {
	mock := &MockLLMLogPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
