FROM ghcr.nju.edu.cn/huggingface/text-generation-inference:2.1.1
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple 
RUN pip install git+https://git-devops.opencsg.com/csg-hub-sdk/csghub-sdk
COPY ./tgi/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh

WORKDIR /workspace/
ENV HUGGINGFACE_HUB_CACHE=/workspace/ \
    HF_HUB_ENABLE_HF_TRANSFER=0
ENV PORT=8000
EXPOSE 8000

ENTRYPOINT ["bash", "/etc/csghub/serve.sh"]