FROM vllm/vllm-openai-cpu:v0.24.0
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip install --no-cache-dir csghub-sdk==0.7.3

WORKDIR /workspace/

COPY ./vllm/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh

ENV HUGGINGFACE_HUB_CACHE=/workspace/ \
    HF_HUB_ENABLE_HF_TRANSFER=0

EXPOSE 8000

ENTRYPOINT ["bash", "/etc/csghub/serve-cpu.sh"]