FROM ghcr.io/huggingface/text-embeddings-inference:1.6
LABEL maintainer="opencsg"

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    python3 \
    python3-dev \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set Python 3.10 as the default Python version
RUN pip3 install --no-cache-dir csghub-sdk==0.4.7

WORKDIR /workspace/

COPY ./tei/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh

ENV HUGGINGFACE_HUB_CACHE=/workspace/ \
    HF_HUB_ENABLE_HF_TRANSFER=0

EXPOSE 8000

ENTRYPOINT ["bash", "/etc/csghub/serve.sh"]