FROM vllm/vllm-openai:v0.8.4
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip install --no-cache-dir csghub-sdk==0.4.8 ray supervisor
RUN apt-get update && apt-get install -y supervisor
RUN mkdir -p /var/log/supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./vllm/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh
RUN chmod +x /vllm-workspace/examples/online_serving/*.sh

WORKDIR /workspace/
ENV HUGGINGFACE_HUB_CACHE=/workspace/ \
    HF_HUB_ENABLE_HF_TRANSFER=0

EXPOSE 8000

ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]