ARG VLLM_METAX_IMAGE=cr.metax-tech.com/public-ai-release/maca/vllm-metax:0.25.0-maca.ai3.8.2.108-torch2.10-py312-ubuntu22.04-amd64
FROM ${VLLM_METAX_IMAGE}

RUN python3 -m pip config set global.index-url https://mirrors.aliyun.com/pypi/simple && \
    python3 -m pip install --no-cache-dir csghub-sdk==0.7.3 && \
    sed -i 's|http://archive.ubuntu.com/ubuntu|http://mirrors.aliyun.com/ubuntu|g' /etc/apt/sources.list && \
    sed -i 's|http://security.ubuntu.com/ubuntu|http://mirrors.aliyun.com/ubuntu|g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y supervisor && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/log/supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./vllm/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh

WORKDIR /workspace/
ENV HUGGINGFACE_HUB_CACHE=/workspace/ \
    HF_HUB_ENABLE_HF_TRANSFER=0

EXPOSE 8000

ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
