FROM vllm/vllm-openai:v0.4.2
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install git+https://git-devops.opencsg.com/csg-hub-sdk/csghub-sdk
RUN pip install ray
COPY ./vllm/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh

WORKDIR /workspace/
ENV HUGGINGFACE_HUB_CACHE=/workspace/ \
    HF_HUB_ENABLE_HF_TRANSFER=0

EXPOSE 8000

ENTRYPOINT ["bash", "/etc/csghub/serve.sh"]