#vllm0.6.2-ubuntu22.04-dtk24.04.3-py3.10-deploy
ARG VLLM_VERSION=vllm0.8.5-ubuntu22.04-dtk25.04-rc7-das1.5-py3.10-20250514-fixpy-rocblas0513-alpha 
FROM image.sourcefind.cn:5000/dcu/admin/base/custom:${VLLM_VERSION}
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip install --no-cache-dir csghub-sdk==0.5.1 ray supervisor docutils==0.16
RUN apt-get update && apt-get install -y supervisor
RUN mkdir -p /var/log/supervisord
COPY ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./vllm/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh
COPY ./vllm/multi-node-serving.sh /vllm-workspace/examples/ray_serving/multi-node-serving.sh
RUN chmod +x /vllm-workspace/examples/ray_serving/*.sh

WORKDIR /workspace/
ENV HUGGINGFACE_HUB_CACHE=/workspace/ \
    HF_HUB_ENABLE_HF_TRANSFER=0

EXPOSE 8000

ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]