
ARG SPACE_NGINX_IMAGE=opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/nginx:latest
FROM ${SPACE_NGINX_IMAGE}
WORKDIR /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
