ARG SPACE_BASE_IMAGE=opencsg-registry.cn-beijing.cr.aliyuncs.com/opencsg_public/space-base:python3.10-cuda12.1.0-1.0.2


FROM ${SPACE_BASE_IMAGE} AS base

USER user
WORKDIR /home/user/app

COPY --link --chown=1000 requirements.txt pre-requirements.txt packages.txt ./

USER root
RUN if [ -s "packages.txt" ]; then \
        apt-get update && \
        xargs -r -a packages.txt apt-get install -y && \
        rm -rf /var/lib/apt/lists/*; \
    else \
        echo "packages.txt is empty or not found, skipping system package installation"; \
    fi

USER user
ARG PyPI=https://mirrors.aliyun.com/pypi/simple/
RUN if [ -n "$PyPI" ]; then \
        pip config set global.index-url "${PyPI}" && \
        pip config set global.trusted-host $(echo "${PyPI}" | sed -n 's|https\?://\([^/]*\)/.*|\1|p'); \
    fi

RUN pip install --no-cache-dir --default-timeout=60 -r pre-requirements.txt && \
    pip install --no-cache-dir --default-timeout=60 -r requirements.txt

COPY --link --chown=1000 ./ ./

ARG HF_ENDPOINT
ENV PYTHONPATH=$HOME/app \
    PYTHONUNBUFFERED=1 \
    GRADIO_ALLOW_FLAGGING=never \
    GRADIO_SERVER_NAME=0.0.0.0 \
    HF_ENDPOINT=${HF_ENDPOINT}

ENTRYPOINT ["./start_entrypoint.sh"]