// Code generated by mockery v2.53.0. DO NOT EDIT.

package rpc

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	rpc "opencsg.com/csghub-server/builder/rpc"
)

// MockAgentHubSvcClient is an autogenerated mock type for the AgentHubSvcClient type
type MockAgentHubSvcClient struct {
	mock.Mock
}

type MockAgentHubSvcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentHubSvcClient) EXPECT() *MockAgentHubSvcClient_Expecter {
	return &MockAgentHubSvcClient_Expecter{mock: &_m.Mock}
}

// CreateAgentInstance provides a mock function with given fields: ctx, userUUID, req
func (_m *MockAgentHubSvcClient) CreateAgentInstance(ctx context.Context, userUUID string, req *rpc.CreateAgentInstanceRequest) (*rpc.CreateAgentInstanceResponse, error) {
	ret := _m.Called(ctx, userUUID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgentInstance")
	}

	var r0 *rpc.CreateAgentInstanceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *rpc.CreateAgentInstanceRequest) (*rpc.CreateAgentInstanceResponse, error)); ok {
		return rf(ctx, userUUID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *rpc.CreateAgentInstanceRequest) *rpc.CreateAgentInstanceResponse); ok {
		r0 = rf(ctx, userUUID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpc.CreateAgentInstanceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *rpc.CreateAgentInstanceRequest) error); ok {
		r1 = rf(ctx, userUUID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentHubSvcClient_CreateAgentInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAgentInstance'
type MockAgentHubSvcClient_CreateAgentInstance_Call struct {
	*mock.Call
}

// CreateAgentInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - req *rpc.CreateAgentInstanceRequest
func (_e *MockAgentHubSvcClient_Expecter) CreateAgentInstance(ctx interface{}, userUUID interface{}, req interface{}) *MockAgentHubSvcClient_CreateAgentInstance_Call {
	return &MockAgentHubSvcClient_CreateAgentInstance_Call{Call: _e.mock.On("CreateAgentInstance", ctx, userUUID, req)}
}

func (_c *MockAgentHubSvcClient_CreateAgentInstance_Call) Run(run func(ctx context.Context, userUUID string, req *rpc.CreateAgentInstanceRequest)) *MockAgentHubSvcClient_CreateAgentInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*rpc.CreateAgentInstanceRequest))
	})
	return _c
}

func (_c *MockAgentHubSvcClient_CreateAgentInstance_Call) Return(_a0 *rpc.CreateAgentInstanceResponse, _a1 error) *MockAgentHubSvcClient_CreateAgentInstance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentHubSvcClient_CreateAgentInstance_Call) RunAndReturn(run func(context.Context, string, *rpc.CreateAgentInstanceRequest) (*rpc.CreateAgentInstanceResponse, error)) *MockAgentHubSvcClient_CreateAgentInstance_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentInstances provides a mock function with given fields: ctx, req
func (_m *MockAgentHubSvcClient) GetAgentInstances(ctx context.Context, req *rpc.GetAgentInstancesRequest) (rpc.GetAgentInstancesResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentInstances")
	}

	var r0 rpc.GetAgentInstancesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.GetAgentInstancesRequest) (rpc.GetAgentInstancesResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.GetAgentInstancesRequest) rpc.GetAgentInstancesResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rpc.GetAgentInstancesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *rpc.GetAgentInstancesRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentHubSvcClient_GetAgentInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentInstances'
type MockAgentHubSvcClient_GetAgentInstances_Call struct {
	*mock.Call
}

// GetAgentInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - req *rpc.GetAgentInstancesRequest
func (_e *MockAgentHubSvcClient_Expecter) GetAgentInstances(ctx interface{}, req interface{}) *MockAgentHubSvcClient_GetAgentInstances_Call {
	return &MockAgentHubSvcClient_GetAgentInstances_Call{Call: _e.mock.On("GetAgentInstances", ctx, req)}
}

func (_c *MockAgentHubSvcClient_GetAgentInstances_Call) Run(run func(ctx context.Context, req *rpc.GetAgentInstancesRequest)) *MockAgentHubSvcClient_GetAgentInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*rpc.GetAgentInstancesRequest))
	})
	return _c
}

func (_c *MockAgentHubSvcClient_GetAgentInstances_Call) Return(_a0 rpc.GetAgentInstancesResponse, _a1 error) *MockAgentHubSvcClient_GetAgentInstances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentHubSvcClient_GetAgentInstances_Call) RunAndReturn(run func(context.Context, *rpc.GetAgentInstancesRequest) (rpc.GetAgentInstancesResponse, error)) *MockAgentHubSvcClient_GetAgentInstances_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentHubSvcClient creates a new instance of MockAgentHubSvcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentHubSvcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentHubSvcClient {
	mock := &MockAgentHubSvcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
