# pull from devel image instead of base
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
# Set bash as the default shell
ENV SHELL=/bin/bash \
    JUPYTERHUB_SERVICE_PREFIX=/proxy/ \
    GRADIO_ROOT_PATH=/proxy/7860/ \
    TZ=Asia/Shanghai \
    NCCL_IB_DISABLE=1 NCCL_P2P_DISABLE=1 \
    HF_HOME=/workspace/.cache \
    DEBIAN_FRONTEND=noninteractive

# Build with some basic utilities
RUN apt-get update && apt-get install -y \
    python3-pip apt-utils \
    wget curl vim \
    git git-lfs \
    supervisor \
    unzip
# set timezone
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

# alias python='python3'
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

# Install the appropriate torch version 
#RUN pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
RUN pip install --no-cache-dir jupyterlab numpy==1.26.4 \
    torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 \
    jupyter-server-proxy==4.4.0 deepspeed \
    gradio-client==1.4.0
# Create a working directory
WORKDIR /etc/csghub
RUN pip install --no-cache-dir vllm==v0.7.3 timm==1.0.11 evalscope==0.12.0
RUN git clone https://gitee.com/xzgan/ms-swift.git --depth 1 --branch v3.2.0.post2
RUN cd ms-swift && pip install --no-cache-dir -e "."
#install flash-attn
#RUN pip install https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.5cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
RUN pip install https://git-devops.opencsg.com/opensource/public_files/-/raw/main/flash_attn-2.7.4.post1+cu12torch2.5cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
# setup supervisord
RUN mkdir -p /var/log/supervisord
COPY swift/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY swift/jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py
COPY swift/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh
#use dark mode
RUN mkdir -p /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension && \
	    echo '{"theme":"JupyterLab Dark"}' > /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings && \
	    mkdir -p /root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension && \
	    echo '{"codeCellConfig":{"lineNumbers":true }}' >   /root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
#fix gradio proxy issue
RUN pip uninstall -y gradio && pip install https://opencsg-public-resource.oss-cn-beijing.aliyuncs.com/csghub/gradio/gradio-5.1.0-py3-none-any.whl


# Create a working directory
WORKDIR /workspace/
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
EXPOSE 8000