# pull from devel image instead of base
FROM modelscope-registry.cn-beijing.cr.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.9.1-py312-torch2.10.0-vllm0.19.1-modelscope1.35.4-swift4.1.3
# Set bash as the default shell
ENV SHELL=/bin/bash \
    JUPYTERHUB_SERVICE_PREFIX=/proxy/ \
    GRADIO_ROOT_PATH=/proxy/7860/ \
    TZ=Asia/Shanghai \
    NCCL_IB_DISABLE=1 NCCL_P2P_DISABLE=1 \
    HF_HOME=/workspace/.cache \
    DEBIAN_FRONTEND=noninteractive

# Build with some basic utilities
RUN apt-get update && apt-get install -y \
    dumb-init && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir ms-swift==4.3.1

COPY swift/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh



# Create a working directory
WORKDIR /workspace/
ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]
CMD ["/etc/csghub/start-job.sh"]