# pull from devel image instead of base
FROM modelscope-registry.cn-beijing.cr.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.9.1-py312-torch2.10.0-vllm0.19.1-modelscope1.35.4-swift4.1.3
# Set bash as the default shell
ENV SHELL=/bin/bash \
    JUPYTERHUB_SERVICE_PREFIX=/proxy/ \
    GRADIO_ROOT_PATH=/proxy/7860/ \
    TZ=Asia/Shanghai \
    NCCL_IB_DISABLE=1 NCCL_P2P_DISABLE=1 \
    HF_HOME=/workspace/.cache \
    DEBIAN_FRONTEND=noninteractive

# Build with some basic utilities
RUN apt-get update && apt-get install -y \
    supervisor && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir jupyterlab jupyter-server-proxy==4.4.0 ms-swift==4.4.2 \
    && pip uninstall -y gradio && pip install --no-cache-dir https://git-devops.opencsg.com/opensource/gradio/-/raw/main/gradio-5.31.0-py3-none-any.whl

# setup supervisord
RUN mkdir -p /var/log/supervisord
COPY swift/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY swift/jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py
COPY swift/ /etc/csghub/
RUN chmod +x /etc/csghub/*.sh /etc/csghub/*.py
#use dark mode
RUN mkdir -p /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension && \
	    echo '{"theme":"JupyterLab Dark"}' > /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings && \
	    mkdir -p /root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension && \
	    echo '{"codeCellConfig":{"lineNumbers":true }}' >   /root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings

# Create a working directory
WORKDIR /workspace/
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
EXPOSE 8000