// Code generated by mockery v2.53.5. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "opencsg.com/csghub-server/builder/store/database"
)

// MockAIGatewayUpstreamHealthStateStore is an autogenerated mock type for the AIGatewayUpstreamHealthStateStore type
type MockAIGatewayUpstreamHealthStateStore struct {
	mock.Mock
}

type MockAIGatewayUpstreamHealthStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIGatewayUpstreamHealthStateStore) EXPECT() *MockAIGatewayUpstreamHealthStateStore_Expecter {
	return &MockAIGatewayUpstreamHealthStateStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, state
func (_m *MockAIGatewayUpstreamHealthStateStore) Create(ctx context.Context, state *database.AIGatewayUpstreamHealthState) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.AIGatewayUpstreamHealthState) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAIGatewayUpstreamHealthStateStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAIGatewayUpstreamHealthStateStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - state *database.AIGatewayUpstreamHealthState
func (_e *MockAIGatewayUpstreamHealthStateStore_Expecter) Create(ctx interface{}, state interface{}) *MockAIGatewayUpstreamHealthStateStore_Create_Call {
	return &MockAIGatewayUpstreamHealthStateStore_Create_Call{Call: _e.mock.On("Create", ctx, state)}
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Create_Call) Run(run func(ctx context.Context, state *database.AIGatewayUpstreamHealthState)) *MockAIGatewayUpstreamHealthStateStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.AIGatewayUpstreamHealthState))
	})
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Create_Call) Return(_a0 error) *MockAIGatewayUpstreamHealthStateStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Create_Call) RunAndReturn(run func(context.Context, *database.AIGatewayUpstreamHealthState) error) *MockAIGatewayUpstreamHealthStateStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUpstreamID provides a mock function with given fields: ctx, upstreamID
func (_m *MockAIGatewayUpstreamHealthStateStore) DeleteByUpstreamID(ctx context.Context, upstreamID int64) error {
	ret := _m.Called(ctx, upstreamID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUpstreamID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, upstreamID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUpstreamID'
type MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call struct {
	*mock.Call
}

// DeleteByUpstreamID is a helper method to define mock.On call
//   - ctx context.Context
//   - upstreamID int64
func (_e *MockAIGatewayUpstreamHealthStateStore_Expecter) DeleteByUpstreamID(ctx interface{}, upstreamID interface{}) *MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call {
	return &MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call{Call: _e.mock.On("DeleteByUpstreamID", ctx, upstreamID)}
}

func (_c *MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call) Run(run func(ctx context.Context, upstreamID int64)) *MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call) Return(_a0 error) *MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call) RunAndReturn(run func(context.Context, int64) error) *MockAIGatewayUpstreamHealthStateStore_DeleteByUpstreamID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllHealthy provides a mock function with given fields: ctx
func (_m *MockAIGatewayUpstreamHealthStateStore) GetAllHealthy(ctx context.Context) ([]database.AIGatewayUpstreamHealthState, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllHealthy")
	}

	var r0 []database.AIGatewayUpstreamHealthState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.AIGatewayUpstreamHealthState, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.AIGatewayUpstreamHealthState); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.AIGatewayUpstreamHealthState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllHealthy'
type MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call struct {
	*mock.Call
}

// GetAllHealthy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAIGatewayUpstreamHealthStateStore_Expecter) GetAllHealthy(ctx interface{}) *MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call {
	return &MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call{Call: _e.mock.On("GetAllHealthy", ctx)}
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call) Run(run func(ctx context.Context)) *MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call) Return(_a0 []database.AIGatewayUpstreamHealthState, _a1 error) *MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call) RunAndReturn(run func(context.Context) ([]database.AIGatewayUpstreamHealthState, error)) *MockAIGatewayUpstreamHealthStateStore_GetAllHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUnhealthy provides a mock function with given fields: ctx
func (_m *MockAIGatewayUpstreamHealthStateStore) GetAllUnhealthy(ctx context.Context) ([]database.AIGatewayUpstreamHealthState, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUnhealthy")
	}

	var r0 []database.AIGatewayUpstreamHealthState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.AIGatewayUpstreamHealthState, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.AIGatewayUpstreamHealthState); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.AIGatewayUpstreamHealthState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUnhealthy'
type MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call struct {
	*mock.Call
}

// GetAllUnhealthy is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAIGatewayUpstreamHealthStateStore_Expecter) GetAllUnhealthy(ctx interface{}) *MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call {
	return &MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call{Call: _e.mock.On("GetAllUnhealthy", ctx)}
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call) Run(run func(ctx context.Context)) *MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call) Return(_a0 []database.AIGatewayUpstreamHealthState, _a1 error) *MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call) RunAndReturn(run func(context.Context) ([]database.AIGatewayUpstreamHealthState, error)) *MockAIGatewayUpstreamHealthStateStore_GetAllUnhealthy_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUpstreamID provides a mock function with given fields: ctx, upstreamID
func (_m *MockAIGatewayUpstreamHealthStateStore) GetByUpstreamID(ctx context.Context, upstreamID int64) (*database.AIGatewayUpstreamHealthState, error) {
	ret := _m.Called(ctx, upstreamID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUpstreamID")
	}

	var r0 *database.AIGatewayUpstreamHealthState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*database.AIGatewayUpstreamHealthState, error)); ok {
		return rf(ctx, upstreamID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *database.AIGatewayUpstreamHealthState); ok {
		r0 = rf(ctx, upstreamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.AIGatewayUpstreamHealthState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, upstreamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUpstreamID'
type MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call struct {
	*mock.Call
}

// GetByUpstreamID is a helper method to define mock.On call
//   - ctx context.Context
//   - upstreamID int64
func (_e *MockAIGatewayUpstreamHealthStateStore_Expecter) GetByUpstreamID(ctx interface{}, upstreamID interface{}) *MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call {
	return &MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call{Call: _e.mock.On("GetByUpstreamID", ctx, upstreamID)}
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call) Run(run func(ctx context.Context, upstreamID int64)) *MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call) Return(_a0 *database.AIGatewayUpstreamHealthState, _a1 error) *MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call) RunAndReturn(run func(context.Context, int64) (*database.AIGatewayUpstreamHealthState, error)) *MockAIGatewayUpstreamHealthStateStore_GetByUpstreamID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, state
func (_m *MockAIGatewayUpstreamHealthStateStore) Update(ctx context.Context, state *database.AIGatewayUpstreamHealthState) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.AIGatewayUpstreamHealthState) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAIGatewayUpstreamHealthStateStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAIGatewayUpstreamHealthStateStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - state *database.AIGatewayUpstreamHealthState
func (_e *MockAIGatewayUpstreamHealthStateStore_Expecter) Update(ctx interface{}, state interface{}) *MockAIGatewayUpstreamHealthStateStore_Update_Call {
	return &MockAIGatewayUpstreamHealthStateStore_Update_Call{Call: _e.mock.On("Update", ctx, state)}
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Update_Call) Run(run func(ctx context.Context, state *database.AIGatewayUpstreamHealthState)) *MockAIGatewayUpstreamHealthStateStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.AIGatewayUpstreamHealthState))
	})
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Update_Call) Return(_a0 error) *MockAIGatewayUpstreamHealthStateStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Update_Call) RunAndReturn(run func(context.Context, *database.AIGatewayUpstreamHealthState) error) *MockAIGatewayUpstreamHealthStateStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, state
func (_m *MockAIGatewayUpstreamHealthStateStore) Upsert(ctx context.Context, state *database.AIGatewayUpstreamHealthState) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.AIGatewayUpstreamHealthState) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAIGatewayUpstreamHealthStateStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockAIGatewayUpstreamHealthStateStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - state *database.AIGatewayUpstreamHealthState
func (_e *MockAIGatewayUpstreamHealthStateStore_Expecter) Upsert(ctx interface{}, state interface{}) *MockAIGatewayUpstreamHealthStateStore_Upsert_Call {
	return &MockAIGatewayUpstreamHealthStateStore_Upsert_Call{Call: _e.mock.On("Upsert", ctx, state)}
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Upsert_Call) Run(run func(ctx context.Context, state *database.AIGatewayUpstreamHealthState)) *MockAIGatewayUpstreamHealthStateStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.AIGatewayUpstreamHealthState))
	})
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Upsert_Call) Return(_a0 error) *MockAIGatewayUpstreamHealthStateStore_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAIGatewayUpstreamHealthStateStore_Upsert_Call) RunAndReturn(run func(context.Context, *database.AIGatewayUpstreamHealthState) error) *MockAIGatewayUpstreamHealthStateStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAIGatewayUpstreamHealthStateStore creates a new instance of MockAIGatewayUpstreamHealthStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIGatewayUpstreamHealthStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIGatewayUpstreamHealthStateStore {
	mock := &MockAIGatewayUpstreamHealthStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
