// Code generated by mockery v2.53.5. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "opencsg.com/csghub-server/builder/store/database"
	types "opencsg.com/csghub-server/common/types"
)

// MockRepositoryAuthorizationStore is an autogenerated mock type for the RepositoryAuthorizationStore type
type MockRepositoryAuthorizationStore struct {
	mock.Mock
}

type MockRepositoryAuthorizationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryAuthorizationStore) EXPECT() *MockRepositoryAuthorizationStore_Expecter {
	return &MockRepositoryAuthorizationStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, authorization
func (_m *MockRepositoryAuthorizationStore) Create(ctx context.Context, authorization *database.RepositoryAuthorization) error {
	ret := _m.Called(ctx, authorization)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.RepositoryAuthorization) error); ok {
		r0 = rf(ctx, authorization)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryAuthorizationStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepositoryAuthorizationStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - authorization *database.RepositoryAuthorization
func (_e *MockRepositoryAuthorizationStore_Expecter) Create(ctx interface{}, authorization interface{}) *MockRepositoryAuthorizationStore_Create_Call {
	return &MockRepositoryAuthorizationStore_Create_Call{Call: _e.mock.On("Create", ctx, authorization)}
}

func (_c *MockRepositoryAuthorizationStore_Create_Call) Run(run func(ctx context.Context, authorization *database.RepositoryAuthorization)) *MockRepositoryAuthorizationStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.RepositoryAuthorization))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_Create_Call) Return(_a0 error) *MockRepositoryAuthorizationStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_Create_Call) RunAndReturn(run func(context.Context, *database.RepositoryAuthorization) error) *MockRepositoryAuthorizationStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, repositoryID, subjectID, subjectType
func (_m *MockRepositoryAuthorizationStore) Delete(ctx context.Context, repositoryID int64, subjectID int64, subjectType types.RepoAuthSubjectType) error {
	ret := _m.Called(ctx, repositoryID, subjectID, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, types.RepoAuthSubjectType) error); ok {
		r0 = rf(ctx, repositoryID, subjectID, subjectType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryAuthorizationStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepositoryAuthorizationStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryID int64
//   - subjectID int64
//   - subjectType types.RepoAuthSubjectType
func (_e *MockRepositoryAuthorizationStore_Expecter) Delete(ctx interface{}, repositoryID interface{}, subjectID interface{}, subjectType interface{}) *MockRepositoryAuthorizationStore_Delete_Call {
	return &MockRepositoryAuthorizationStore_Delete_Call{Call: _e.mock.On("Delete", ctx, repositoryID, subjectID, subjectType)}
}

func (_c *MockRepositoryAuthorizationStore_Delete_Call) Run(run func(ctx context.Context, repositoryID int64, subjectID int64, subjectType types.RepoAuthSubjectType)) *MockRepositoryAuthorizationStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(types.RepoAuthSubjectType))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_Delete_Call) Return(_a0 error) *MockRepositoryAuthorizationStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_Delete_Call) RunAndReturn(run func(context.Context, int64, int64, types.RepoAuthSubjectType) error) *MockRepositoryAuthorizationStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySubject provides a mock function with given fields: ctx, subjectType, subjectID
func (_m *MockRepositoryAuthorizationStore) DeleteBySubject(ctx context.Context, subjectType types.RepoAuthSubjectType, subjectID int64) error {
	ret := _m.Called(ctx, subjectType, subjectID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySubject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RepoAuthSubjectType, int64) error); ok {
		r0 = rf(ctx, subjectType, subjectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryAuthorizationStore_DeleteBySubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySubject'
type MockRepositoryAuthorizationStore_DeleteBySubject_Call struct {
	*mock.Call
}

// DeleteBySubject is a helper method to define mock.On call
//   - ctx context.Context
//   - subjectType types.RepoAuthSubjectType
//   - subjectID int64
func (_e *MockRepositoryAuthorizationStore_Expecter) DeleteBySubject(ctx interface{}, subjectType interface{}, subjectID interface{}) *MockRepositoryAuthorizationStore_DeleteBySubject_Call {
	return &MockRepositoryAuthorizationStore_DeleteBySubject_Call{Call: _e.mock.On("DeleteBySubject", ctx, subjectType, subjectID)}
}

func (_c *MockRepositoryAuthorizationStore_DeleteBySubject_Call) Run(run func(ctx context.Context, subjectType types.RepoAuthSubjectType, subjectID int64)) *MockRepositoryAuthorizationStore_DeleteBySubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RepoAuthSubjectType), args[2].(int64))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_DeleteBySubject_Call) Return(_a0 error) *MockRepositoryAuthorizationStore_DeleteBySubject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_DeleteBySubject_Call) RunAndReturn(run func(context.Context, types.RepoAuthSubjectType, int64) error) *MockRepositoryAuthorizationStore_DeleteBySubject_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, repositoryID, subjectID, subjectType
func (_m *MockRepositoryAuthorizationStore) Find(ctx context.Context, repositoryID int64, subjectID int64, subjectType types.RepoAuthSubjectType) (*database.RepositoryAuthorization, error) {
	ret := _m.Called(ctx, repositoryID, subjectID, subjectType)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *database.RepositoryAuthorization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, types.RepoAuthSubjectType) (*database.RepositoryAuthorization, error)); ok {
		return rf(ctx, repositoryID, subjectID, subjectType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, types.RepoAuthSubjectType) *database.RepositoryAuthorization); ok {
		r0 = rf(ctx, repositoryID, subjectID, subjectType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.RepositoryAuthorization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, types.RepoAuthSubjectType) error); ok {
		r1 = rf(ctx, repositoryID, subjectID, subjectType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryAuthorizationStore_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockRepositoryAuthorizationStore_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryID int64
//   - subjectID int64
//   - subjectType types.RepoAuthSubjectType
func (_e *MockRepositoryAuthorizationStore_Expecter) Find(ctx interface{}, repositoryID interface{}, subjectID interface{}, subjectType interface{}) *MockRepositoryAuthorizationStore_Find_Call {
	return &MockRepositoryAuthorizationStore_Find_Call{Call: _e.mock.On("Find", ctx, repositoryID, subjectID, subjectType)}
}

func (_c *MockRepositoryAuthorizationStore_Find_Call) Run(run func(ctx context.Context, repositoryID int64, subjectID int64, subjectType types.RepoAuthSubjectType)) *MockRepositoryAuthorizationStore_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(types.RepoAuthSubjectType))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_Find_Call) Return(_a0 *database.RepositoryAuthorization, _a1 error) *MockRepositoryAuthorizationStore_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_Find_Call) RunAndReturn(run func(context.Context, int64, int64, types.RepoAuthSubjectType) (*database.RepositoryAuthorization, error)) *MockRepositoryAuthorizationStore_Find_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, repositoryID, per, page
func (_m *MockRepositoryAuthorizationStore) List(ctx context.Context, repositoryID int64, per int, page int) ([]database.RepositoryAuthorization, int, error) {
	ret := _m.Called(ctx, repositoryID, per, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []database.RepositoryAuthorization
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]database.RepositoryAuthorization, int, error)); ok {
		return rf(ctx, repositoryID, per, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []database.RepositoryAuthorization); ok {
		r0 = rf(ctx, repositoryID, per, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.RepositoryAuthorization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) int); ok {
		r1 = rf(ctx, repositoryID, per, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int) error); ok {
		r2 = rf(ctx, repositoryID, per, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepositoryAuthorizationStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepositoryAuthorizationStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryID int64
//   - per int
//   - page int
func (_e *MockRepositoryAuthorizationStore_Expecter) List(ctx interface{}, repositoryID interface{}, per interface{}, page interface{}) *MockRepositoryAuthorizationStore_List_Call {
	return &MockRepositoryAuthorizationStore_List_Call{Call: _e.mock.On("List", ctx, repositoryID, per, page)}
}

func (_c *MockRepositoryAuthorizationStore_List_Call) Run(run func(ctx context.Context, repositoryID int64, per int, page int)) *MockRepositoryAuthorizationStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_List_Call) Return(_a0 []database.RepositoryAuthorization, _a1 int, _a2 error) *MockRepositoryAuthorizationStore_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_List_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]database.RepositoryAuthorization, int, error)) *MockRepositoryAuthorizationStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByRepository provides a mock function with given fields: ctx, repositoryID
func (_m *MockRepositoryAuthorizationStore) ListByRepository(ctx context.Context, repositoryID int64) ([]database.RepositoryAuthorization, error) {
	ret := _m.Called(ctx, repositoryID)
	if len(ret) == 0 {
		panic("no return value specified for ListByRepository")
	}
	var r0 []database.RepositoryAuthorization
	if rf, ok := ret.Get(0).(func(context.Context, int64) []database.RepositoryAuthorization); ok {
		r0 = rf(ctx, repositoryID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]database.RepositoryAuthorization)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, repositoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockRepositoryAuthorizationStore_ListByRepository_Call struct{ *mock.Call }

func (_e *MockRepositoryAuthorizationStore_Expecter) ListByRepository(ctx interface{}, repositoryID interface{}) *MockRepositoryAuthorizationStore_ListByRepository_Call {
	return &MockRepositoryAuthorizationStore_ListByRepository_Call{Call: _e.mock.On("ListByRepository", ctx, repositoryID)}
}

func (_c *MockRepositoryAuthorizationStore_ListByRepository_Call) Run(run func(context.Context, int64)) *MockRepositoryAuthorizationStore_ListByRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_ListByRepository_Call) Return(_a0 []database.RepositoryAuthorization, _a1 error) *MockRepositoryAuthorizationStore_ListByRepository_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_ListByRepository_Call) RunAndReturn(run func(context.Context, int64) ([]database.RepositoryAuthorization, error)) *MockRepositoryAuthorizationStore_ListByRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, repositoryID, subjectID, subjectType, role
func (_m *MockRepositoryAuthorizationStore) UpdateRole(ctx context.Context, repositoryID int64, subjectID int64, subjectType types.RepoAuthSubjectType, role types.UserRole) error {
	ret := _m.Called(ctx, repositoryID, subjectID, subjectType, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, types.RepoAuthSubjectType, types.UserRole) error); ok {
		r0 = rf(ctx, repositoryID, subjectID, subjectType, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryAuthorizationStore_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockRepositoryAuthorizationStore_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryID int64
//   - subjectID int64
//   - subjectType types.RepoAuthSubjectType
//   - role types.UserRole
func (_e *MockRepositoryAuthorizationStore_Expecter) UpdateRole(ctx interface{}, repositoryID interface{}, subjectID interface{}, subjectType interface{}, role interface{}) *MockRepositoryAuthorizationStore_UpdateRole_Call {
	return &MockRepositoryAuthorizationStore_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, repositoryID, subjectID, subjectType, role)}
}

func (_c *MockRepositoryAuthorizationStore_UpdateRole_Call) Run(run func(ctx context.Context, repositoryID int64, subjectID int64, subjectType types.RepoAuthSubjectType, role types.UserRole)) *MockRepositoryAuthorizationStore_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(types.RepoAuthSubjectType), args[4].(types.UserRole))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_UpdateRole_Call) Return(_a0 error) *MockRepositoryAuthorizationStore_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_UpdateRole_Call) RunAndReturn(run func(context.Context, int64, int64, types.RepoAuthSubjectType, types.UserRole) error) *MockRepositoryAuthorizationStore_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByRepository provides a mock function with given fields: ctx, repositoryID
func (_m *MockRepositoryAuthorizationStore) DeleteByRepository(ctx context.Context, repositoryID int64) error {
	ret := _m.Called(ctx, repositoryID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRepository")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, repositoryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryAuthorizationStore_DeleteByRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRepository'
type MockRepositoryAuthorizationStore_DeleteByRepository_Call struct {
	*mock.Call
}

// DeleteByRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryID int64
func (_e *MockRepositoryAuthorizationStore_Expecter) DeleteByRepository(ctx interface{}, repositoryID interface{}) *MockRepositoryAuthorizationStore_DeleteByRepository_Call {
	return &MockRepositoryAuthorizationStore_DeleteByRepository_Call{Call: _e.mock.On("DeleteByRepository", ctx, repositoryID)}
}

func (_c *MockRepositoryAuthorizationStore_DeleteByRepository_Call) Run(run func(ctx context.Context, repositoryID int64)) *MockRepositoryAuthorizationStore_DeleteByRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepositoryAuthorizationStore_DeleteByRepository_Call) Return(_a0 error) *MockRepositoryAuthorizationStore_DeleteByRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryAuthorizationStore_DeleteByRepository_Call) RunAndReturn(run func(context.Context, int64) error) *MockRepositoryAuthorizationStore_DeleteByRepository_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySubject provides a mock function with given fields: ctx, subjectType, subjectID
func (_m *MockRepositoryAuthorizationStore) ListBySubject(ctx context.Context, subjectType types.RepoAuthSubjectType, subjectID int64) ([]database.RepositoryAuthorization, error) {
	ret := _m.Called(ctx, subjectType, subjectID)
	if len(ret) == 0 {
		panic("no return value specified for ListBySubject")
	}
	var r0 []database.RepositoryAuthorization
	if rf, ok := ret.Get(0).(func(context.Context, types.RepoAuthSubjectType, int64) []database.RepositoryAuthorization); ok {
		r0 = rf(ctx, subjectType, subjectID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]database.RepositoryAuthorization)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, types.RepoAuthSubjectType, int64) error); ok {
		r1 = rf(ctx, subjectType, subjectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockRepositoryAuthorizationStore_ListBySubject_Call struct{ *mock.Call }

func (_e *MockRepositoryAuthorizationStore_Expecter) ListBySubject(ctx interface{}, subjectType interface{}, subjectID interface{}) *MockRepositoryAuthorizationStore_ListBySubject_Call {
	return &MockRepositoryAuthorizationStore_ListBySubject_Call{Call: _e.mock.On("ListBySubject", ctx, subjectType, subjectID)}
}
func (_c *MockRepositoryAuthorizationStore_ListBySubject_Call) Run(run func(context.Context, types.RepoAuthSubjectType, int64)) *MockRepositoryAuthorizationStore_ListBySubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RepoAuthSubjectType), args[2].(int64))
	})
	return _c
}
func (_c *MockRepositoryAuthorizationStore_ListBySubject_Call) Return(_a0 []database.RepositoryAuthorization, _a1 error) *MockRepositoryAuthorizationStore_ListBySubject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
func (_c *MockRepositoryAuthorizationStore_ListBySubject_Call) RunAndReturn(run func(context.Context, types.RepoAuthSubjectType, int64) ([]database.RepositoryAuthorization, error)) *MockRepositoryAuthorizationStore_ListBySubject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryAuthorizationStore creates a new instance of MockRepositoryAuthorizationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryAuthorizationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryAuthorizationStore {
	mock := &MockRepositoryAuthorizationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
