// Code generated by mockery v2.53.6. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepoDescriptionStore is an autogenerated mock type for the RepoDescriptionStore type
type MockRepoDescriptionStore struct {
	mock.Mock
}

type MockRepoDescriptionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoDescriptionStore) EXPECT() *MockRepoDescriptionStore_Expecter {
	return &MockRepoDescriptionStore_Expecter{mock: &_m.Mock}
}

// UpdateDescriptionIfEmpty provides a mock function with given fields: ctx, repoID, description
func (_m *MockRepoDescriptionStore) UpdateDescriptionIfEmpty(ctx context.Context, repoID int64, description string) (bool, error) {
	ret := _m.Called(ctx, repoID, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDescriptionIfEmpty")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return rf(ctx, repoID, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = rf(ctx, repoID, description)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, repoID, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDescriptionIfEmpty'
type MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call struct {
	*mock.Call
}

// UpdateDescriptionIfEmpty is a helper method to define mock.On call
//   - ctx context.Context
//   - repoID int64
//   - description string
func (_e *MockRepoDescriptionStore_Expecter) UpdateDescriptionIfEmpty(ctx interface{}, repoID interface{}, description interface{}) *MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call {
	return &MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call{Call: _e.mock.On("UpdateDescriptionIfEmpty", ctx, repoID, description)}
}

func (_c *MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call) Run(run func(ctx context.Context, repoID int64, description string)) *MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call) Return(_a0 bool, _a1 error) *MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call) RunAndReturn(run func(context.Context, int64, string) (bool, error)) *MockRepoDescriptionStore_UpdateDescriptionIfEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepoDescriptionStore creates a new instance of MockRepoDescriptionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoDescriptionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoDescriptionStore {
	mock := &MockRepoDescriptionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
