// Code generated by mockery v2.53.6. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHistoryArchiveCheckpointStore is an autogenerated mock type for the HistoryArchiveCheckpointStore type
type MockHistoryArchiveCheckpointStore struct {
	mock.Mock
}

type MockHistoryArchiveCheckpointStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryArchiveCheckpointStore) EXPECT() *MockHistoryArchiveCheckpointStore_Expecter {
	return &MockHistoryArchiveCheckpointStore_Expecter{mock: &_m.Mock}
}

// GetLastPK provides a mock function with given fields: ctx, tableName
func (_m *MockHistoryArchiveCheckpointStore) GetLastPK(ctx context.Context, tableName string) (string, error) {
	ret := _m.Called(ctx, tableName)

	if len(ret) == 0 {
		panic("no return value specified for GetLastPK")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tableName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tableName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tableName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryArchiveCheckpointStore_GetLastPK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastPK'
type MockHistoryArchiveCheckpointStore_GetLastPK_Call struct {
	*mock.Call
}

// GetLastPK is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName string
func (_e *MockHistoryArchiveCheckpointStore_Expecter) GetLastPK(ctx interface{}, tableName interface{}) *MockHistoryArchiveCheckpointStore_GetLastPK_Call {
	return &MockHistoryArchiveCheckpointStore_GetLastPK_Call{Call: _e.mock.On("GetLastPK", ctx, tableName)}
}

func (_c *MockHistoryArchiveCheckpointStore_GetLastPK_Call) Run(run func(ctx context.Context, tableName string)) *MockHistoryArchiveCheckpointStore_GetLastPK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHistoryArchiveCheckpointStore_GetLastPK_Call) Return(_a0 string, _a1 error) *MockHistoryArchiveCheckpointStore_GetLastPK_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryArchiveCheckpointStore_GetLastPK_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockHistoryArchiveCheckpointStore_GetLastPK_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLastPK provides a mock function with given fields: ctx, tableName, lastPK
func (_m *MockHistoryArchiveCheckpointStore) SaveLastPK(ctx context.Context, tableName string, lastPK string) error {
	ret := _m.Called(ctx, tableName, lastPK)

	if len(ret) == 0 {
		panic("no return value specified for SaveLastPK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tableName, lastPK)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHistoryArchiveCheckpointStore_SaveLastPK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLastPK'
type MockHistoryArchiveCheckpointStore_SaveLastPK_Call struct {
	*mock.Call
}

// SaveLastPK is a helper method to define mock.On call
//   - ctx context.Context
//   - tableName string
//   - lastPK string
func (_e *MockHistoryArchiveCheckpointStore_Expecter) SaveLastPK(ctx interface{}, tableName interface{}, lastPK interface{}) *MockHistoryArchiveCheckpointStore_SaveLastPK_Call {
	return &MockHistoryArchiveCheckpointStore_SaveLastPK_Call{Call: _e.mock.On("SaveLastPK", ctx, tableName, lastPK)}
}

func (_c *MockHistoryArchiveCheckpointStore_SaveLastPK_Call) Run(run func(ctx context.Context, tableName string, lastPK string)) *MockHistoryArchiveCheckpointStore_SaveLastPK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockHistoryArchiveCheckpointStore_SaveLastPK_Call) Return(_a0 error) *MockHistoryArchiveCheckpointStore_SaveLastPK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHistoryArchiveCheckpointStore_SaveLastPK_Call) RunAndReturn(run func(context.Context, string, string) error) *MockHistoryArchiveCheckpointStore_SaveLastPK_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHistoryArchiveCheckpointStore creates a new instance of MockHistoryArchiveCheckpointStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryArchiveCheckpointStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryArchiveCheckpointStore {
	mock := &MockHistoryArchiveCheckpointStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
