// Code generated by mockery v2.53.6. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryDeletionMirrorTaskStore is an autogenerated mock type for the RepositoryDeletionMirrorTaskStore type
type MockRepositoryDeletionMirrorTaskStore struct {
	mock.Mock
}

type MockRepositoryDeletionMirrorTaskStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryDeletionMirrorTaskStore) EXPECT() *MockRepositoryDeletionMirrorTaskStore_Expecter {
	return &MockRepositoryDeletionMirrorTaskStore_Expecter{mock: &_m.Mock}
}

// FindCurrentMirrorTaskID provides a mock function with given fields: ctx, repositoryID
func (_m *MockRepositoryDeletionMirrorTaskStore) FindCurrentMirrorTaskID(ctx context.Context, repositoryID int64) (int64, error) {
	ret := _m.Called(ctx, repositoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindCurrentMirrorTaskID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, repositoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, repositoryID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, repositoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCurrentMirrorTaskID'
type MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call struct {
	*mock.Call
}

// FindCurrentMirrorTaskID is a helper method to define mock.On call
//   - ctx context.Context
//   - repositoryID int64
func (_e *MockRepositoryDeletionMirrorTaskStore_Expecter) FindCurrentMirrorTaskID(ctx interface{}, repositoryID interface{}) *MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call {
	return &MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call{Call: _e.mock.On("FindCurrentMirrorTaskID", ctx, repositoryID)}
}

func (_c *MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call) Run(run func(ctx context.Context, repositoryID int64)) *MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call) Return(_a0 int64, _a1 error) *MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockRepositoryDeletionMirrorTaskStore_FindCurrentMirrorTaskID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryDeletionMirrorTaskStore creates a new instance of MockRepositoryDeletionMirrorTaskStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryDeletionMirrorTaskStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryDeletionMirrorTaskStore {
	mock := &MockRepositoryDeletionMirrorTaskStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
