// Code generated by mockery v2.53.6. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "opencsg.com/csghub-server/builder/store/database"
)

// MockHistoryArchiveStore is an autogenerated mock type for the HistoryArchiveStore type
type MockHistoryArchiveStore struct {
	mock.Mock
}

type MockHistoryArchiveStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryArchiveStore) EXPECT() *MockHistoryArchiveStore_Expecter {
	return &MockHistoryArchiveStore_Expecter{mock: &_m.Mock}
}

// Backfill provides a mock function with given fields: ctx, batchSize, tables
func (_m *MockHistoryArchiveStore) Backfill(ctx context.Context, batchSize int, tables []database.HistoryArchiveTable) ([]database.HistoryArchiveResult, error) {
	ret := _m.Called(ctx, batchSize, tables)

	if len(ret) == 0 {
		panic("no return value specified for Backfill")
	}

	var r0 []database.HistoryArchiveResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []database.HistoryArchiveTable) ([]database.HistoryArchiveResult, error)); ok {
		return rf(ctx, batchSize, tables)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []database.HistoryArchiveTable) []database.HistoryArchiveResult); ok {
		r0 = rf(ctx, batchSize, tables)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.HistoryArchiveResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []database.HistoryArchiveTable) error); ok {
		r1 = rf(ctx, batchSize, tables)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryArchiveStore_Backfill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Backfill'
type MockHistoryArchiveStore_Backfill_Call struct {
	*mock.Call
}

// Backfill is a helper method to define mock.On call
//   - ctx context.Context
//   - batchSize int
//   - tables []database.HistoryArchiveTable
func (_e *MockHistoryArchiveStore_Expecter) Backfill(ctx interface{}, batchSize interface{}, tables interface{}) *MockHistoryArchiveStore_Backfill_Call {
	return &MockHistoryArchiveStore_Backfill_Call{Call: _e.mock.On("Backfill", ctx, batchSize, tables)}
}

func (_c *MockHistoryArchiveStore_Backfill_Call) Run(run func(ctx context.Context, batchSize int, tables []database.HistoryArchiveTable)) *MockHistoryArchiveStore_Backfill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].([]database.HistoryArchiveTable))
	})
	return _c
}

func (_c *MockHistoryArchiveStore_Backfill_Call) Return(_a0 []database.HistoryArchiveResult, _a1 error) *MockHistoryArchiveStore_Backfill_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryArchiveStore_Backfill_Call) RunAndReturn(run func(context.Context, int, []database.HistoryArchiveTable) ([]database.HistoryArchiveResult, error)) *MockHistoryArchiveStore_Backfill_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureSyncTriggers provides a mock function with given fields: ctx, enable
func (_m *MockHistoryArchiveStore) EnsureSyncTriggers(ctx context.Context, enable bool) error {
	ret := _m.Called(ctx, enable)

	if len(ret) == 0 {
		panic("no return value specified for EnsureSyncTriggers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, enable)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHistoryArchiveStore_EnsureSyncTriggers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureSyncTriggers'
type MockHistoryArchiveStore_EnsureSyncTriggers_Call struct {
	*mock.Call
}

// EnsureSyncTriggers is a helper method to define mock.On call
//   - ctx context.Context
//   - enable bool
func (_e *MockHistoryArchiveStore_Expecter) EnsureSyncTriggers(ctx interface{}, enable interface{}) *MockHistoryArchiveStore_EnsureSyncTriggers_Call {
	return &MockHistoryArchiveStore_EnsureSyncTriggers_Call{Call: _e.mock.On("EnsureSyncTriggers", ctx, enable)}
}

func (_c *MockHistoryArchiveStore_EnsureSyncTriggers_Call) Run(run func(ctx context.Context, enable bool)) *MockHistoryArchiveStore_EnsureSyncTriggers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockHistoryArchiveStore_EnsureSyncTriggers_Call) Return(_a0 error) *MockHistoryArchiveStore_EnsureSyncTriggers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHistoryArchiveStore_EnsureSyncTriggers_Call) RunAndReturn(run func(context.Context, bool) error) *MockHistoryArchiveStore_EnsureSyncTriggers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHistoryArchiveStore creates a new instance of MockHistoryArchiveStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryArchiveStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryArchiveStore {
	mock := &MockHistoryArchiveStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
