// Code generated by mockery v2.53.0. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "opencsg.com/csghub-server/builder/store/database"
)

// MockAgentInstanceSessionHistoryStore is an autogenerated mock type for the AgentInstanceSessionHistoryStore type
type MockAgentInstanceSessionHistoryStore struct {
	mock.Mock
}

type MockAgentInstanceSessionHistoryStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentInstanceSessionHistoryStore) EXPECT() *MockAgentInstanceSessionHistoryStore_Expecter {
	return &MockAgentInstanceSessionHistoryStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, history
func (_m *MockAgentInstanceSessionHistoryStore) Create(ctx context.Context, history *database.AgentInstanceSessionHistory) error {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.AgentInstanceSessionHistory) error); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentInstanceSessionHistoryStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAgentInstanceSessionHistoryStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - history *database.AgentInstanceSessionHistory
func (_e *MockAgentInstanceSessionHistoryStore_Expecter) Create(ctx interface{}, history interface{}) *MockAgentInstanceSessionHistoryStore_Create_Call {
	return &MockAgentInstanceSessionHistoryStore_Create_Call{Call: _e.mock.On("Create", ctx, history)}
}

func (_c *MockAgentInstanceSessionHistoryStore_Create_Call) Run(run func(ctx context.Context, history *database.AgentInstanceSessionHistory)) *MockAgentInstanceSessionHistoryStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.AgentInstanceSessionHistory))
	})
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Create_Call) Return(_a0 error) *MockAgentInstanceSessionHistoryStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Create_Call) RunAndReturn(run func(context.Context, *database.AgentInstanceSessionHistory) error) *MockAgentInstanceSessionHistoryStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAgentInstanceSessionHistoryStore) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentInstanceSessionHistoryStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAgentInstanceSessionHistoryStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAgentInstanceSessionHistoryStore_Expecter) Delete(ctx interface{}, id interface{}) *MockAgentInstanceSessionHistoryStore_Delete_Call {
	return &MockAgentInstanceSessionHistoryStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAgentInstanceSessionHistoryStore_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockAgentInstanceSessionHistoryStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Delete_Call) Return(_a0 error) *MockAgentInstanceSessionHistoryStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockAgentInstanceSessionHistoryStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockAgentInstanceSessionHistoryStore) FindByID(ctx context.Context, id int64) (*database.AgentInstanceSessionHistory, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *database.AgentInstanceSessionHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*database.AgentInstanceSessionHistory, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *database.AgentInstanceSessionHistory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.AgentInstanceSessionHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentInstanceSessionHistoryStore_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAgentInstanceSessionHistoryStore_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAgentInstanceSessionHistoryStore_Expecter) FindByID(ctx interface{}, id interface{}) *MockAgentInstanceSessionHistoryStore_FindByID_Call {
	return &MockAgentInstanceSessionHistoryStore_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAgentInstanceSessionHistoryStore_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockAgentInstanceSessionHistoryStore_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_FindByID_Call) Return(_a0 *database.AgentInstanceSessionHistory, _a1 error) *MockAgentInstanceSessionHistoryStore_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*database.AgentInstanceSessionHistory, error)) *MockAgentInstanceSessionHistoryStore_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUUID provides a mock function with given fields: ctx, uuid
func (_m *MockAgentInstanceSessionHistoryStore) FindByUUID(ctx context.Context, uuid string) (*database.AgentInstanceSessionHistory, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for FindByUUID")
	}

	var r0 *database.AgentInstanceSessionHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*database.AgentInstanceSessionHistory, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *database.AgentInstanceSessionHistory); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.AgentInstanceSessionHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentInstanceSessionHistoryStore_FindByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUUID'
type MockAgentInstanceSessionHistoryStore_FindByUUID_Call struct {
	*mock.Call
}

// FindByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockAgentInstanceSessionHistoryStore_Expecter) FindByUUID(ctx interface{}, uuid interface{}) *MockAgentInstanceSessionHistoryStore_FindByUUID_Call {
	return &MockAgentInstanceSessionHistoryStore_FindByUUID_Call{Call: _e.mock.On("FindByUUID", ctx, uuid)}
}

func (_c *MockAgentInstanceSessionHistoryStore_FindByUUID_Call) Run(run func(ctx context.Context, uuid string)) *MockAgentInstanceSessionHistoryStore_FindByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_FindByUUID_Call) Return(_a0 *database.AgentInstanceSessionHistory, _a1 error) *MockAgentInstanceSessionHistoryStore_FindByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_FindByUUID_Call) RunAndReturn(run func(context.Context, string) (*database.AgentInstanceSessionHistory, error)) *MockAgentInstanceSessionHistoryStore_FindByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockAgentInstanceSessionHistoryStore) ListBySessionID(ctx context.Context, sessionID int64) ([]database.AgentInstanceSessionHistory, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListBySessionID")
	}

	var r0 []database.AgentInstanceSessionHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]database.AgentInstanceSessionHistory, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []database.AgentInstanceSessionHistory); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.AgentInstanceSessionHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentInstanceSessionHistoryStore_ListBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBySessionID'
type MockAgentInstanceSessionHistoryStore_ListBySessionID_Call struct {
	*mock.Call
}

// ListBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID int64
func (_e *MockAgentInstanceSessionHistoryStore_Expecter) ListBySessionID(ctx interface{}, sessionID interface{}) *MockAgentInstanceSessionHistoryStore_ListBySessionID_Call {
	return &MockAgentInstanceSessionHistoryStore_ListBySessionID_Call{Call: _e.mock.On("ListBySessionID", ctx, sessionID)}
}

func (_c *MockAgentInstanceSessionHistoryStore_ListBySessionID_Call) Run(run func(ctx context.Context, sessionID int64)) *MockAgentInstanceSessionHistoryStore_ListBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_ListBySessionID_Call) Return(_a0 []database.AgentInstanceSessionHistory, _a1 error) *MockAgentInstanceSessionHistoryStore_ListBySessionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_ListBySessionID_Call) RunAndReturn(run func(context.Context, int64) ([]database.AgentInstanceSessionHistory, error)) *MockAgentInstanceSessionHistoryStore_ListBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// Rewrite provides a mock function with given fields: ctx, originalMsgUUID, history
func (_m *MockAgentInstanceSessionHistoryStore) Rewrite(ctx context.Context, originalMsgUUID string, history *database.AgentInstanceSessionHistory) error {
	ret := _m.Called(ctx, originalMsgUUID, history)

	if len(ret) == 0 {
		panic("no return value specified for Rewrite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *database.AgentInstanceSessionHistory) error); ok {
		r0 = rf(ctx, originalMsgUUID, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentInstanceSessionHistoryStore_Rewrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rewrite'
type MockAgentInstanceSessionHistoryStore_Rewrite_Call struct {
	*mock.Call
}

// Rewrite is a helper method to define mock.On call
//   - ctx context.Context
//   - originalMsgUUID string
//   - history *database.AgentInstanceSessionHistory
func (_e *MockAgentInstanceSessionHistoryStore_Expecter) Rewrite(ctx interface{}, originalMsgUUID interface{}, history interface{}) *MockAgentInstanceSessionHistoryStore_Rewrite_Call {
	return &MockAgentInstanceSessionHistoryStore_Rewrite_Call{Call: _e.mock.On("Rewrite", ctx, originalMsgUUID, history)}
}

func (_c *MockAgentInstanceSessionHistoryStore_Rewrite_Call) Run(run func(ctx context.Context, originalMsgUUID string, history *database.AgentInstanceSessionHistory)) *MockAgentInstanceSessionHistoryStore_Rewrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*database.AgentInstanceSessionHistory))
	})
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Rewrite_Call) Return(_a0 error) *MockAgentInstanceSessionHistoryStore_Rewrite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Rewrite_Call) RunAndReturn(run func(context.Context, string, *database.AgentInstanceSessionHistory) error) *MockAgentInstanceSessionHistoryStore_Rewrite_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, history
func (_m *MockAgentInstanceSessionHistoryStore) Update(ctx context.Context, history *database.AgentInstanceSessionHistory) error {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.AgentInstanceSessionHistory) error); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentInstanceSessionHistoryStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAgentInstanceSessionHistoryStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - history *database.AgentInstanceSessionHistory
func (_e *MockAgentInstanceSessionHistoryStore_Expecter) Update(ctx interface{}, history interface{}) *MockAgentInstanceSessionHistoryStore_Update_Call {
	return &MockAgentInstanceSessionHistoryStore_Update_Call{Call: _e.mock.On("Update", ctx, history)}
}

func (_c *MockAgentInstanceSessionHistoryStore_Update_Call) Run(run func(ctx context.Context, history *database.AgentInstanceSessionHistory)) *MockAgentInstanceSessionHistoryStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.AgentInstanceSessionHistory))
	})
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Update_Call) Return(_a0 error) *MockAgentInstanceSessionHistoryStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentInstanceSessionHistoryStore_Update_Call) RunAndReturn(run func(context.Context, *database.AgentInstanceSessionHistory) error) *MockAgentInstanceSessionHistoryStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentInstanceSessionHistoryStore creates a new instance of MockAgentInstanceSessionHistoryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentInstanceSessionHistoryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentInstanceSessionHistoryStore {
	mock := &MockAgentInstanceSessionHistoryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
