// Code generated by mockery v2.53.6. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "opencsg.com/csghub-server/builder/store/database"

	types "opencsg.com/csghub-server/common/types"
)

// MockAccountStatisticsStore is an autogenerated mock type for the AccountStatisticsStore type
type MockAccountStatisticsStore struct {
	mock.Mock
}

type MockAccountStatisticsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountStatisticsStore) EXPECT() *MockAccountStatisticsStore_Expecter {
	return &MockAccountStatisticsStore_Expecter{mock: &_m.Mock}
}

// ListByUserIDAndDate provides a mock function with given fields: ctx, req
func (_m *MockAccountStatisticsStore) ListByUserIDAndDate(ctx context.Context, req types.AcctBillsReq) (database.AccountStatisticsRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserIDAndDate")
	}

	var r0 database.AccountStatisticsRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AcctBillsReq) (database.AccountStatisticsRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AcctBillsReq) database.AccountStatisticsRes); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(database.AccountStatisticsRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AcctBillsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountStatisticsStore_ListByUserIDAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserIDAndDate'
type MockAccountStatisticsStore_ListByUserIDAndDate_Call struct {
	*mock.Call
}

// ListByUserIDAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - req types.AcctBillsReq
func (_e *MockAccountStatisticsStore_Expecter) ListByUserIDAndDate(ctx interface{}, req interface{}) *MockAccountStatisticsStore_ListByUserIDAndDate_Call {
	return &MockAccountStatisticsStore_ListByUserIDAndDate_Call{Call: _e.mock.On("ListByUserIDAndDate", ctx, req)}
}

func (_c *MockAccountStatisticsStore_ListByUserIDAndDate_Call) Run(run func(ctx context.Context, req types.AcctBillsReq)) *MockAccountStatisticsStore_ListByUserIDAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AcctBillsReq))
	})
	return _c
}

func (_c *MockAccountStatisticsStore_ListByUserIDAndDate_Call) Return(_a0 database.AccountStatisticsRes, _a1 error) *MockAccountStatisticsStore_ListByUserIDAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountStatisticsStore_ListByUserIDAndDate_Call) RunAndReturn(run func(context.Context, types.AcctBillsReq) (database.AccountStatisticsRes, error)) *MockAccountStatisticsStore_ListByUserIDAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// ListStatisticsDetailByUserID provides a mock function with given fields: ctx, req
func (_m *MockAccountStatisticsStore) ListStatisticsDetailByUserID(ctx context.Context, req types.AcctBillsDetailReq) (database.AccountStatisticsDetailRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListStatisticsDetailByUserID")
	}

	var r0 database.AccountStatisticsDetailRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AcctBillsDetailReq) (database.AccountStatisticsDetailRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AcctBillsDetailReq) database.AccountStatisticsDetailRes); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(database.AccountStatisticsDetailRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AcctBillsDetailReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStatisticsDetailByUserID'
type MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call struct {
	*mock.Call
}

// ListStatisticsDetailByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - req types.AcctBillsDetailReq
func (_e *MockAccountStatisticsStore_Expecter) ListStatisticsDetailByUserID(ctx interface{}, req interface{}) *MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call {
	return &MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call{Call: _e.mock.On("ListStatisticsDetailByUserID", ctx, req)}
}

func (_c *MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call) Run(run func(ctx context.Context, req types.AcctBillsDetailReq)) *MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AcctBillsDetailReq))
	})
	return _c
}

func (_c *MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call) Return(_a0 database.AccountStatisticsDetailRes, _a1 error) *MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call) RunAndReturn(run func(context.Context, types.AcctBillsDetailReq) (database.AccountStatisticsDetailRes, error)) *MockAccountStatisticsStore_ListStatisticsDetailByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SummaryByUserIDAndDate provides a mock function with given fields: ctx, req
func (_m *MockAccountStatisticsStore) SummaryByUserIDAndDate(ctx context.Context, req types.AcctBillsReq) (database.AccountStatisticsSummaryRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SummaryByUserIDAndDate")
	}

	var r0 database.AccountStatisticsSummaryRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.AcctBillsReq) (database.AccountStatisticsSummaryRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.AcctBillsReq) database.AccountStatisticsSummaryRes); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(database.AccountStatisticsSummaryRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.AcctBillsReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountStatisticsStore_SummaryByUserIDAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SummaryByUserIDAndDate'
type MockAccountStatisticsStore_SummaryByUserIDAndDate_Call struct {
	*mock.Call
}

// SummaryByUserIDAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - req types.AcctBillsReq
func (_e *MockAccountStatisticsStore_Expecter) SummaryByUserIDAndDate(ctx interface{}, req interface{}) *MockAccountStatisticsStore_SummaryByUserIDAndDate_Call {
	return &MockAccountStatisticsStore_SummaryByUserIDAndDate_Call{Call: _e.mock.On("SummaryByUserIDAndDate", ctx, req)}
}

func (_c *MockAccountStatisticsStore_SummaryByUserIDAndDate_Call) Run(run func(ctx context.Context, req types.AcctBillsReq)) *MockAccountStatisticsStore_SummaryByUserIDAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.AcctBillsReq))
	})
	return _c
}

func (_c *MockAccountStatisticsStore_SummaryByUserIDAndDate_Call) Return(_a0 database.AccountStatisticsSummaryRes, _a1 error) *MockAccountStatisticsStore_SummaryByUserIDAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountStatisticsStore_SummaryByUserIDAndDate_Call) RunAndReturn(run func(context.Context, types.AcctBillsReq) (database.AccountStatisticsSummaryRes, error)) *MockAccountStatisticsStore_SummaryByUserIDAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountStatisticsStore creates a new instance of MockAccountStatisticsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountStatisticsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountStatisticsStore {
	mock := &MockAccountStatisticsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
