// Code generated by mockery v2.53.5. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "opencsg.com/csghub-server/builder/store/database"
)

// MockModelStore is an autogenerated mock type for the ModelStore type
type MockModelStore struct {
	mock.Mock
}

type MockModelStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelStore) EXPECT() *MockModelStore_Expecter {
	return &MockModelStore_Expecter{mock: &_m.Mock}
}

// ByID provides a mock function with given fields: ctx, id
func (_m *MockModelStore) ByID(ctx context.Context, id int64) (*database.Model, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ByID")
	}

	var r0 *database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*database.Model, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *database.Model); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_ByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByID'
type MockModelStore_ByID_Call struct {
	*mock.Call
}

// ByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockModelStore_Expecter) ByID(ctx interface{}, id interface{}) *MockModelStore_ByID_Call {
	return &MockModelStore_ByID_Call{Call: _e.mock.On("ByID", ctx, id)}
}

func (_c *MockModelStore_ByID_Call) Run(run func(ctx context.Context, id int64)) *MockModelStore_ByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockModelStore_ByID_Call) Return(_a0 *database.Model, _a1 error) *MockModelStore_ByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_ByID_Call) RunAndReturn(run func(context.Context, int64) (*database.Model, error)) *MockModelStore_ByID_Call {
	_c.Call.Return(run)
	return _c
}

// ByOrgPath provides a mock function with given fields: ctx, namespace, per, page, onlyPublic
func (_m *MockModelStore) ByOrgPath(ctx context.Context, namespace string, per int, page int, onlyPublic bool) ([]database.Model, int, error) {
	ret := _m.Called(ctx, namespace, per, page, onlyPublic)

	if len(ret) == 0 {
		panic("no return value specified for ByOrgPath")
	}

	var r0 []database.Model
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) ([]database.Model, int, error)); ok {
		return rf(ctx, namespace, per, page, onlyPublic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) []database.Model); ok {
		r0 = rf(ctx, namespace, per, page, onlyPublic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, bool) int); ok {
		r1 = rf(ctx, namespace, per, page, onlyPublic)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, bool) error); ok {
		r2 = rf(ctx, namespace, per, page, onlyPublic)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockModelStore_ByOrgPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByOrgPath'
type MockModelStore_ByOrgPath_Call struct {
	*mock.Call
}

// ByOrgPath is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - per int
//   - page int
//   - onlyPublic bool
func (_e *MockModelStore_Expecter) ByOrgPath(ctx interface{}, namespace interface{}, per interface{}, page interface{}, onlyPublic interface{}) *MockModelStore_ByOrgPath_Call {
	return &MockModelStore_ByOrgPath_Call{Call: _e.mock.On("ByOrgPath", ctx, namespace, per, page, onlyPublic)}
}

func (_c *MockModelStore_ByOrgPath_Call) Run(run func(ctx context.Context, namespace string, per int, page int, onlyPublic bool)) *MockModelStore_ByOrgPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(bool))
	})
	return _c
}

func (_c *MockModelStore_ByOrgPath_Call) Return(models []database.Model, total int, err error) *MockModelStore_ByOrgPath_Call {
	_c.Call.Return(models, total, err)
	return _c
}

func (_c *MockModelStore_ByOrgPath_Call) RunAndReturn(run func(context.Context, string, int, int, bool) ([]database.Model, int, error)) *MockModelStore_ByOrgPath_Call {
	_c.Call.Return(run)
	return _c
}

// ByRepoID provides a mock function with given fields: ctx, repoID
func (_m *MockModelStore) ByRepoID(ctx context.Context, repoID int64) (*database.Model, error) {
	ret := _m.Called(ctx, repoID)

	if len(ret) == 0 {
		panic("no return value specified for ByRepoID")
	}

	var r0 *database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*database.Model, error)); ok {
		return rf(ctx, repoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *database.Model); ok {
		r0 = rf(ctx, repoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, repoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_ByRepoID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByRepoID'
type MockModelStore_ByRepoID_Call struct {
	*mock.Call
}

// ByRepoID is a helper method to define mock.On call
//   - ctx context.Context
//   - repoID int64
func (_e *MockModelStore_Expecter) ByRepoID(ctx interface{}, repoID interface{}) *MockModelStore_ByRepoID_Call {
	return &MockModelStore_ByRepoID_Call{Call: _e.mock.On("ByRepoID", ctx, repoID)}
}

func (_c *MockModelStore_ByRepoID_Call) Run(run func(ctx context.Context, repoID int64)) *MockModelStore_ByRepoID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockModelStore_ByRepoID_Call) Return(_a0 *database.Model, _a1 error) *MockModelStore_ByRepoID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_ByRepoID_Call) RunAndReturn(run func(context.Context, int64) (*database.Model, error)) *MockModelStore_ByRepoID_Call {
	_c.Call.Return(run)
	return _c
}

// ByRepoIDs provides a mock function with given fields: ctx, repoIDs
func (_m *MockModelStore) ByRepoIDs(ctx context.Context, repoIDs []int64) ([]database.Model, error) {
	ret := _m.Called(ctx, repoIDs)

	if len(ret) == 0 {
		panic("no return value specified for ByRepoIDs")
	}

	var r0 []database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]database.Model, error)); ok {
		return rf(ctx, repoIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []database.Model); ok {
		r0 = rf(ctx, repoIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, repoIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_ByRepoIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByRepoIDs'
type MockModelStore_ByRepoIDs_Call struct {
	*mock.Call
}

// ByRepoIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - repoIDs []int64
func (_e *MockModelStore_Expecter) ByRepoIDs(ctx interface{}, repoIDs interface{}) *MockModelStore_ByRepoIDs_Call {
	return &MockModelStore_ByRepoIDs_Call{Call: _e.mock.On("ByRepoIDs", ctx, repoIDs)}
}

func (_c *MockModelStore_ByRepoIDs_Call) Run(run func(ctx context.Context, repoIDs []int64)) *MockModelStore_ByRepoIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockModelStore_ByRepoIDs_Call) Return(models []database.Model, err error) *MockModelStore_ByRepoIDs_Call {
	_c.Call.Return(models, err)
	return _c
}

func (_c *MockModelStore_ByRepoIDs_Call) RunAndReturn(run func(context.Context, []int64) ([]database.Model, error)) *MockModelStore_ByRepoIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ByUsername provides a mock function with given fields: ctx, username, per, page, onlyPublic
func (_m *MockModelStore) ByUsername(ctx context.Context, username string, per int, page int, onlyPublic bool) ([]database.Model, int, error) {
	ret := _m.Called(ctx, username, per, page, onlyPublic)

	if len(ret) == 0 {
		panic("no return value specified for ByUsername")
	}

	var r0 []database.Model
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) ([]database.Model, int, error)); ok {
		return rf(ctx, username, per, page, onlyPublic)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, bool) []database.Model); ok {
		r0 = rf(ctx, username, per, page, onlyPublic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, bool) int); ok {
		r1 = rf(ctx, username, per, page, onlyPublic)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, bool) error); ok {
		r2 = rf(ctx, username, per, page, onlyPublic)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockModelStore_ByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByUsername'
type MockModelStore_ByUsername_Call struct {
	*mock.Call
}

// ByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - per int
//   - page int
//   - onlyPublic bool
func (_e *MockModelStore_Expecter) ByUsername(ctx interface{}, username interface{}, per interface{}, page interface{}, onlyPublic interface{}) *MockModelStore_ByUsername_Call {
	return &MockModelStore_ByUsername_Call{Call: _e.mock.On("ByUsername", ctx, username, per, page, onlyPublic)}
}

func (_c *MockModelStore_ByUsername_Call) Run(run func(ctx context.Context, username string, per int, page int, onlyPublic bool)) *MockModelStore_ByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int), args[4].(bool))
	})
	return _c
}

func (_c *MockModelStore_ByUsername_Call) Return(models []database.Model, total int, err error) *MockModelStore_ByUsername_Call {
	_c.Call.Return(models, total, err)
	return _c
}

func (_c *MockModelStore_ByUsername_Call) RunAndReturn(run func(context.Context, string, int, int, bool) ([]database.Model, int, error)) *MockModelStore_ByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with given fields: ctx
func (_m *MockModelStore) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockModelStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockModelStore_Expecter) Count(ctx interface{}) *MockModelStore_Count_Call {
	return &MockModelStore_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockModelStore_Count_Call) Run(run func(ctx context.Context)) *MockModelStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockModelStore_Count_Call) Return(count int, err error) *MockModelStore_Count_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *MockModelStore_Count_Call) RunAndReturn(run func(context.Context) (int, error)) *MockModelStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, input
func (_m *MockModelStore) Create(ctx context.Context, input database.Model) (*database.Model, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Model) (*database.Model, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Model) *database.Model); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Model) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockModelStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input database.Model
func (_e *MockModelStore_Expecter) Create(ctx interface{}, input interface{}) *MockModelStore_Create_Call {
	return &MockModelStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockModelStore_Create_Call) Run(run func(ctx context.Context, input database.Model)) *MockModelStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.Model))
	})
	return _c
}

func (_c *MockModelStore_Create_Call) Return(_a0 *database.Model, _a1 error) *MockModelStore_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_Create_Call) RunAndReturn(run func(context.Context, database.Model) (*database.Model, error)) *MockModelStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAndUpdateRepoPath provides a mock function with given fields: ctx, input, path
func (_m *MockModelStore) CreateAndUpdateRepoPath(ctx context.Context, input database.Model, path string) (*database.Model, error) {
	ret := _m.Called(ctx, input, path)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndUpdateRepoPath")
	}

	var r0 *database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Model, string) (*database.Model, error)); ok {
		return rf(ctx, input, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Model, string) *database.Model); ok {
		r0 = rf(ctx, input, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Model, string) error); ok {
		r1 = rf(ctx, input, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_CreateAndUpdateRepoPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAndUpdateRepoPath'
type MockModelStore_CreateAndUpdateRepoPath_Call struct {
	*mock.Call
}

// CreateAndUpdateRepoPath is a helper method to define mock.On call
//   - ctx context.Context
//   - input database.Model
//   - path string
func (_e *MockModelStore_Expecter) CreateAndUpdateRepoPath(ctx interface{}, input interface{}, path interface{}) *MockModelStore_CreateAndUpdateRepoPath_Call {
	return &MockModelStore_CreateAndUpdateRepoPath_Call{Call: _e.mock.On("CreateAndUpdateRepoPath", ctx, input, path)}
}

func (_c *MockModelStore_CreateAndUpdateRepoPath_Call) Run(run func(ctx context.Context, input database.Model, path string)) *MockModelStore_CreateAndUpdateRepoPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.Model), args[2].(string))
	})
	return _c
}

func (_c *MockModelStore_CreateAndUpdateRepoPath_Call) Return(_a0 *database.Model, _a1 error) *MockModelStore_CreateAndUpdateRepoPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_CreateAndUpdateRepoPath_Call) RunAndReturn(run func(context.Context, database.Model, string) (*database.Model, error)) *MockModelStore_CreateAndUpdateRepoPath_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIfNotExist provides a mock function with given fields: ctx, input
func (_m *MockModelStore) CreateIfNotExist(ctx context.Context, input database.Model) (*database.Model, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateIfNotExist")
	}

	var r0 *database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Model) (*database.Model, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Model) *database.Model); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Model) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_CreateIfNotExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIfNotExist'
type MockModelStore_CreateIfNotExist_Call struct {
	*mock.Call
}

// CreateIfNotExist is a helper method to define mock.On call
//   - ctx context.Context
//   - input database.Model
func (_e *MockModelStore_Expecter) CreateIfNotExist(ctx interface{}, input interface{}) *MockModelStore_CreateIfNotExist_Call {
	return &MockModelStore_CreateIfNotExist_Call{Call: _e.mock.On("CreateIfNotExist", ctx, input)}
}

func (_c *MockModelStore_CreateIfNotExist_Call) Run(run func(ctx context.Context, input database.Model)) *MockModelStore_CreateIfNotExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.Model))
	})
	return _c
}

func (_c *MockModelStore_CreateIfNotExist_Call) Return(_a0 *database.Model, _a1 error) *MockModelStore_CreateIfNotExist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_CreateIfNotExist_Call) RunAndReturn(run func(context.Context, database.Model) (*database.Model, error)) *MockModelStore_CreateIfNotExist_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, input
func (_m *MockModelStore) Delete(ctx context.Context, input database.Model) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Model) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockModelStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockModelStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - input database.Model
func (_e *MockModelStore_Expecter) Delete(ctx interface{}, input interface{}) *MockModelStore_Delete_Call {
	return &MockModelStore_Delete_Call{Call: _e.mock.On("Delete", ctx, input)}
}

func (_c *MockModelStore_Delete_Call) Run(run func(ctx context.Context, input database.Model)) *MockModelStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.Model))
	})
	return _c
}

func (_c *MockModelStore_Delete_Call) Return(_a0 error) *MockModelStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockModelStore_Delete_Call) RunAndReturn(run func(context.Context, database.Model) error) *MockModelStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByPath provides a mock function with given fields: ctx, namespace, name
func (_m *MockModelStore) FindByPath(ctx context.Context, namespace string, name string) (*database.Model, error) {
	ret := _m.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByPath")
	}

	var r0 *database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*database.Model, error)); ok {
		return rf(ctx, namespace, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *database.Model); ok {
		r0 = rf(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_FindByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByPath'
type MockModelStore_FindByPath_Call struct {
	*mock.Call
}

// FindByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockModelStore_Expecter) FindByPath(ctx interface{}, namespace interface{}, name interface{}) *MockModelStore_FindByPath_Call {
	return &MockModelStore_FindByPath_Call{Call: _e.mock.On("FindByPath", ctx, namespace, name)}
}

func (_c *MockModelStore_FindByPath_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockModelStore_FindByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockModelStore_FindByPath_Call) Return(_a0 *database.Model, _a1 error) *MockModelStore_FindByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_FindByPath_Call) RunAndReturn(run func(context.Context, string, string) (*database.Model, error)) *MockModelStore_FindByPath_Call {
	_c.Call.Return(run)
	return _c
}

// ListByPath provides a mock function with given fields: ctx, paths
func (_m *MockModelStore) ListByPath(ctx context.Context, paths []string) ([]database.Model, error) {
	ret := _m.Called(ctx, paths)

	if len(ret) == 0 {
		panic("no return value specified for ListByPath")
	}

	var r0 []database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]database.Model, error)); ok {
		return rf(ctx, paths)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []database.Model); ok {
		r0 = rf(ctx, paths)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, paths)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_ListByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByPath'
type MockModelStore_ListByPath_Call struct {
	*mock.Call
}

// ListByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []string
func (_e *MockModelStore_Expecter) ListByPath(ctx interface{}, paths interface{}) *MockModelStore_ListByPath_Call {
	return &MockModelStore_ListByPath_Call{Call: _e.mock.On("ListByPath", ctx, paths)}
}

func (_c *MockModelStore_ListByPath_Call) Run(run func(ctx context.Context, paths []string)) *MockModelStore_ListByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockModelStore_ListByPath_Call) Return(_a0 []database.Model, _a1 error) *MockModelStore_ListByPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_ListByPath_Call) RunAndReturn(run func(context.Context, []string) ([]database.Model, error)) *MockModelStore_ListByPath_Call {
	_c.Call.Return(run)
	return _c
}

// PublicCount provides a mock function with given fields: ctx
func (_m *MockModelStore) PublicCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PublicCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_PublicCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicCount'
type MockModelStore_PublicCount_Call struct {
	*mock.Call
}

// PublicCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockModelStore_Expecter) PublicCount(ctx interface{}) *MockModelStore_PublicCount_Call {
	return &MockModelStore_PublicCount_Call{Call: _e.mock.On("PublicCount", ctx)}
}

func (_c *MockModelStore_PublicCount_Call) Run(run func(ctx context.Context)) *MockModelStore_PublicCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockModelStore_PublicCount_Call) Return(count int, err error) *MockModelStore_PublicCount_Call {
	_c.Call.Return(count, err)
	return _c
}

func (_c *MockModelStore_PublicCount_Call) RunAndReturn(run func(context.Context) (int, error)) *MockModelStore_PublicCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, input
func (_m *MockModelStore) Update(ctx context.Context, input database.Model) (*database.Model, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *database.Model
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Model) (*database.Model, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.Model) *database.Model); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.Model) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockModelStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - input database.Model
func (_e *MockModelStore_Expecter) Update(ctx interface{}, input interface{}) *MockModelStore_Update_Call {
	return &MockModelStore_Update_Call{Call: _e.mock.On("Update", ctx, input)}
}

func (_c *MockModelStore_Update_Call) Run(run func(ctx context.Context, input database.Model)) *MockModelStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.Model))
	})
	return _c
}

func (_c *MockModelStore_Update_Call) Return(_a0 *database.Model, _a1 error) *MockModelStore_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelStore_Update_Call) RunAndReturn(run func(context.Context, database.Model) (*database.Model, error)) *MockModelStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UserLikesModels provides a mock function with given fields: ctx, userID, per, page
func (_m *MockModelStore) UserLikesModels(ctx context.Context, userID int64, per int, page int) ([]database.Model, int, error) {
	ret := _m.Called(ctx, userID, per, page)

	if len(ret) == 0 {
		panic("no return value specified for UserLikesModels")
	}

	var r0 []database.Model
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]database.Model, int, error)); ok {
		return rf(ctx, userID, per, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []database.Model); ok {
		r0 = rf(ctx, userID, per, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Model)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) int); ok {
		r1 = rf(ctx, userID, per, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int) error); ok {
		r2 = rf(ctx, userID, per, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockModelStore_UserLikesModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserLikesModels'
type MockModelStore_UserLikesModels_Call struct {
	*mock.Call
}

// UserLikesModels is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - per int
//   - page int
func (_e *MockModelStore_Expecter) UserLikesModels(ctx interface{}, userID interface{}, per interface{}, page interface{}) *MockModelStore_UserLikesModels_Call {
	return &MockModelStore_UserLikesModels_Call{Call: _e.mock.On("UserLikesModels", ctx, userID, per, page)}
}

func (_c *MockModelStore_UserLikesModels_Call) Run(run func(ctx context.Context, userID int64, per int, page int)) *MockModelStore_UserLikesModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockModelStore_UserLikesModels_Call) Return(models []database.Model, total int, err error) *MockModelStore_UserLikesModels_Call {
	_c.Call.Return(models, total, err)
	return _c
}

func (_c *MockModelStore_UserLikesModels_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]database.Model, int, error)) *MockModelStore_UserLikesModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModelStore creates a new instance of MockModelStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelStore {
	mock := &MockModelStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
