// Code generated by mockery v2.53.5. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	database "opencsg.com/csghub-server/builder/store/database"

	types "opencsg.com/csghub-server/common/types"
)

// MockAgentInstanceSchedulerTaskStore is an autogenerated mock type for the AgentInstanceSchedulerTaskStore type
type MockAgentInstanceSchedulerTaskStore struct {
	mock.Mock
}

type MockAgentInstanceSchedulerTaskStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentInstanceSchedulerTaskStore) EXPECT() *MockAgentInstanceSchedulerTaskStore_Expecter {
	return &MockAgentInstanceSchedulerTaskStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, task
func (_m *MockAgentInstanceSchedulerTaskStore) Create(ctx context.Context, task *database.AgentInstanceSchedulerTask) (*database.AgentInstanceSchedulerTask, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *database.AgentInstanceSchedulerTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.AgentInstanceSchedulerTask) (*database.AgentInstanceSchedulerTask, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *database.AgentInstanceSchedulerTask) *database.AgentInstanceSchedulerTask); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.AgentInstanceSchedulerTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *database.AgentInstanceSchedulerTask) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentInstanceSchedulerTaskStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAgentInstanceSchedulerTaskStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task *database.AgentInstanceSchedulerTask
func (_e *MockAgentInstanceSchedulerTaskStore_Expecter) Create(ctx interface{}, task interface{}) *MockAgentInstanceSchedulerTaskStore_Create_Call {
	return &MockAgentInstanceSchedulerTaskStore_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockAgentInstanceSchedulerTaskStore_Create_Call) Run(run func(ctx context.Context, task *database.AgentInstanceSchedulerTask)) *MockAgentInstanceSchedulerTaskStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.AgentInstanceSchedulerTask))
	})
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_Create_Call) Return(_a0 *database.AgentInstanceSchedulerTask, _a1 error) *MockAgentInstanceSchedulerTaskStore_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_Create_Call) RunAndReturn(run func(context.Context, *database.AgentInstanceSchedulerTask) (*database.AgentInstanceSchedulerTask, error)) *MockAgentInstanceSchedulerTaskStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockAgentInstanceSchedulerTaskStore) FindByID(ctx context.Context, id int64) (*database.AgentInstanceSchedulerTask, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *database.AgentInstanceSchedulerTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*database.AgentInstanceSchedulerTask, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *database.AgentInstanceSchedulerTask); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.AgentInstanceSchedulerTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentInstanceSchedulerTaskStore_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockAgentInstanceSchedulerTaskStore_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAgentInstanceSchedulerTaskStore_Expecter) FindByID(ctx interface{}, id interface{}) *MockAgentInstanceSchedulerTaskStore_FindByID_Call {
	return &MockAgentInstanceSchedulerTaskStore_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockAgentInstanceSchedulerTaskStore_FindByID_Call) Run(run func(ctx context.Context, id int64)) *MockAgentInstanceSchedulerTaskStore_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_FindByID_Call) Return(_a0 *database.AgentInstanceSchedulerTask, _a1 error) *MockAgentInstanceSchedulerTaskStore_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*database.AgentInstanceSchedulerTask, error)) *MockAgentInstanceSchedulerTaskStore_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByInstanceID provides a mock function with given fields: ctx, userUUID, instanceID, filter, per, page
func (_m *MockAgentInstanceSchedulerTaskStore) ListByInstanceID(ctx context.Context, userUUID string, instanceID int64, filter types.AgentSchedulerTaskFilter, per int, page int) ([]database.AgentInstanceSchedulerTask, int, error) {
	ret := _m.Called(ctx, userUUID, instanceID, filter, per, page)

	if len(ret) == 0 {
		panic("no return value specified for ListByInstanceID")
	}

	var r0 []database.AgentInstanceSchedulerTask
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, types.AgentSchedulerTaskFilter, int, int) ([]database.AgentInstanceSchedulerTask, int, error)); ok {
		return rf(ctx, userUUID, instanceID, filter, per, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, types.AgentSchedulerTaskFilter, int, int) []database.AgentInstanceSchedulerTask); ok {
		r0 = rf(ctx, userUUID, instanceID, filter, per, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.AgentInstanceSchedulerTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, types.AgentSchedulerTaskFilter, int, int) int); ok {
		r1 = rf(ctx, userUUID, instanceID, filter, per, page)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, types.AgentSchedulerTaskFilter, int, int) error); ok {
		r2 = rf(ctx, userUUID, instanceID, filter, per, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByInstanceID'
type MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call struct {
	*mock.Call
}

// ListByInstanceID is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - instanceID int64
//   - filter types.AgentSchedulerTaskFilter
//   - per int
//   - page int
func (_e *MockAgentInstanceSchedulerTaskStore_Expecter) ListByInstanceID(ctx interface{}, userUUID interface{}, instanceID interface{}, filter interface{}, per interface{}, page interface{}) *MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call {
	return &MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call{Call: _e.mock.On("ListByInstanceID", ctx, userUUID, instanceID, filter, per, page)}
}

func (_c *MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call) Run(run func(ctx context.Context, userUUID string, instanceID int64, filter types.AgentSchedulerTaskFilter, per int, page int)) *MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(types.AgentSchedulerTaskFilter), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call) Return(_a0 []database.AgentInstanceSchedulerTask, _a1 int, _a2 error) *MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call) RunAndReturn(run func(context.Context, string, int64, types.AgentSchedulerTaskFilter, int, int) ([]database.AgentInstanceSchedulerTask, int, error)) *MockAgentInstanceSchedulerTaskStore_ListByInstanceID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, task
func (_m *MockAgentInstanceSchedulerTaskStore) Update(ctx context.Context, task *database.AgentInstanceSchedulerTask) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *database.AgentInstanceSchedulerTask) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAgentInstanceSchedulerTaskStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAgentInstanceSchedulerTaskStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - task *database.AgentInstanceSchedulerTask
func (_e *MockAgentInstanceSchedulerTaskStore_Expecter) Update(ctx interface{}, task interface{}) *MockAgentInstanceSchedulerTaskStore_Update_Call {
	return &MockAgentInstanceSchedulerTaskStore_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockAgentInstanceSchedulerTaskStore_Update_Call) Run(run func(ctx context.Context, task *database.AgentInstanceSchedulerTask)) *MockAgentInstanceSchedulerTaskStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*database.AgentInstanceSchedulerTask))
	})
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_Update_Call) Return(_a0 error) *MockAgentInstanceSchedulerTaskStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentInstanceSchedulerTaskStore_Update_Call) RunAndReturn(run func(context.Context, *database.AgentInstanceSchedulerTask) error) *MockAgentInstanceSchedulerTaskStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentInstanceSchedulerTaskStore creates a new instance of MockAgentInstanceSchedulerTaskStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentInstanceSchedulerTaskStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentInstanceSchedulerTaskStore {
	mock := &MockAgentInstanceSchedulerTaskStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
