## Golang Lint ############################################
.go-lint:
  image: ${ALI_ACR_REGISTRY}/golangci/golangci-lint:latest
  stage: test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  services:
    - name: ${ALI_ACR_REGISTRY}/docker:27.3-dind
      command: ["--feature=containerd-snapshotter", "--experimental"]
      alias: docker
  needs: []
  before_script:
    - go install gotest.tools/gotestsum@latest
    - go install github.com/axw/gocov/gocov@latest
    - go install github.com/AlekSi/gocov-xml@latest
  script:
    - gotestsum --junitfile report.xml --format testname -- -tags="$BUILD_TAG" -coverprofile=coverage.out -covermode=atomic ./...
    - go tool cover -func=coverage.out
    - gocov convert coverage.out | gocov-xml > coverage.xml
  interruptible: true
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml
  cache:
    key: lint-cache
    paths:
      - .cache
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - docker

test-ce:
  extends: .go-lint
  variables:
    BUILD_TAG: ""

test-ee:
  extends: .go-lint
  variables:
    BUILD_TAG: "ee"

test-saas:
  extends: .go-lint
  variables:
    BUILD_TAG: "saas"
